import {auth,db} from './firebase';
import {collection,doc,getDoc,getDocs,limit,onSnapshot,orderBy,query,setDoc,serverTimestamp} from 'firebase/firestore';
export type AnalyticsEventType='session'|'share'|'bookmark'|'reaction'|'complete';
function visitorId(){if(typeof window==='undefined')return'server';const k='offscrpt:analytics-visitor:v2';try{const x=localStorage.getItem(k);if(x)return x;const v=crypto.randomUUID();localStorage.setItem(k,v);return v}catch{return`anon-${Math.random().toString(36).slice(2)}`}}
function sessionId(slug:string){if(typeof window==='undefined')return`server-${slug}`;const k=`offscrpt:analytics-session:${slug}`;try{const x=sessionStorage.getItem(k);if(x)return x;const v=crypto.randomUUID();sessionStorage.setItem(k,v);return v}catch{return`${Date.now()}-${Math.random().toString(36).slice(2)}`}}
const device=()=>typeof navigator==='undefined'?'unknown':`${navigator.platform||'unknown'} · ${window.innerWidth}x${window.innerHeight}`;
export async function upsertArticleAnalyticsSession(slug:string,patch:any={}){if(!slug)return;const sid=sessionId(slug),uid=auth.currentUser?.uid||'',visitor=uid?'':visitorId(),ref=doc(db,'articles',slug,'analytics',sid),existing=await getDoc(ref).catch(()=>null);const prev:any=existing?.exists?.()?existing.data():{};const maxScroll=Math.max(Number(prev.maxScrollPercent||0),Math.min(100,Number(patch.maxScrollPercent||0)));const base:any={id:sid,type:'session',slug,userId:uid,visitorId:visitor,device:device(),source:String(patch.source||prev.source||'article'),...(existing?.exists?.()?{}:{openedAt:serverTimestamp()}),lastSeenAt:serverTimestamp(),maxScrollPercent:maxScroll,durationMs:Math.max(Number(prev.durationMs||0),Math.min(86400000,Number(patch.durationMs||0))),completed:!!(patch.completed||prev.completed),currentSection:String(patch.currentSection||prev.currentSection||'').slice(0,200),scrollY:Math.max(0,Math.min(100000000,Number(patch.scrollY??prev.scrollY??0))),seriesId:String(patch.seriesId||prev.seriesId||'').slice(0,200),seriesOrder:Number(patch.seriesOrder??prev.seriesOrder??0)};await setDoc(ref,base,{merge:true});}
export async function recordArticleAnalyticsEvent(slug:string,type:Exclude<AnalyticsEventType,'session'>,payload:any={}){if(!slug)return;await setDoc(doc(collection(db,'articles',slug,'analytics')),{type,slug,userId:auth.currentUser?.uid||'',visitorId:auth.currentUser?'':visitorId(),createdAt:serverTimestamp(),...payload});}
export interface ArticleAnalyticsAggregate{views:number;uniqueReaders:number;averageReadingTimeMs:number;completionRate:number;scrollDepth:number;reactions:number;bookmarks:number;comments:number;shares:number;returnReaders:number;funnel:{opened:number;p25:number;p50:number;p75:number;completed:number};}
const empty=():ArticleAnalyticsAggregate=>({views:0,uniqueReaders:0,averageReadingTimeMs:0,completionRate:0,scrollDepth:0,reactions:0,bookmarks:0,comments:0,shares:0,returnReaders:0,funnel:{opened:0,p25:0,p50:0,p75:0,completed:0}});
function dateValue(v:any){return v?.toDate?v.toDate().getTime():typeof v==='string'?Date.parse(v):0}
export async function getArticleAnalyticsAggregate(slug:string,fallbackViews=0,days:number| 'all'='all'):Promise<ArticleAnalyticsAggregate>{const base=empty();base.views=fallbackViews;try{const snap=await getDocs(query(collection(db,'articles',slug,'analytics'),limit(1000)));const cutoff=days==='all'?0:Date.now()-days*86400000;const rows=snap.docs.map(d=>d.data() as any).filter(x=>dateValue(x.lastSeenAt||x.createdAt||x.openedAt)>=cutoff);const sessions=rows.filter(x=>x.type==='session');const events=rows.filter(x=>x.type!=='session');base.views=Math.max(base.views,sessions.length);const ids=new Set<string>();sessions.forEach(s=>{const k=s.userId||s.visitorId;if(k)ids.add(k)});base.uniqueReaders=ids.size;const counts:Record<string,number>={};sessions.forEach(s=>{const k=s.userId||s.visitorId;if(k)counts[k]=(counts[k]||0)+1});base.returnReaders=Object.values(counts).filter(n=>n>1).reduce((n)=>n+1,0);if(sessions.length){base.averageReadingTimeMs=Math.round(sessions.reduce((n,s)=>n+Number(s.durationMs||0),0)/sessions.length);base.scrollDepth=Math.round(sessions.reduce((n,s)=>n+Number(s.maxScrollPercent||0),0)/sessions.length);base.completionRate=Math.round(100*sessions.filter(s=>s.completed||Number(s.maxScrollPercent||0)>=100).length/sessions.length)}base.funnel={opened:sessions.length,p25:sessions.filter(s=>Number(s.maxScrollPercent||0)>=25).length,p50:sessions.filter(s=>Number(s.maxScrollPercent||0)>=50).length,p75:sessions.filter(s=>Number(s.maxScrollPercent||0)>=75).length,completed:sessions.filter(s=>s.completed||Number(s.maxScrollPercent||0)>=100).length};base.shares=events.filter(e=>e.type==='share').length;base.bookmarks=events.filter(e=>e.type==='bookmark'&&e.active!==false).length;base.reactions=events.filter(e=>e.type==='reaction'&&e.active!==false).length;return base}catch{return base}}
export async function subscribeArticleAnalytics(slug:string,cb:(a:ArticleAnalyticsAggregate)=>void,days:number|'all'='all'){if(!slug){cb(empty());return()=>{}};return onSnapshot(query(collection(db,'articles',slug,'analytics'),limit(1000)),async()=>cb(await getArticleAnalyticsAggregate(slug,0,days)),()=>cb(empty()));}
