import { db, auth } from './firebase';
import { collection, doc, setDoc, getDoc, getDocs, updateDoc, deleteDoc, serverTimestamp, query, where, limit } from 'firebase/firestore';
import type { Article } from '../types';
export type CreatorCollaboratorRole='owner'|'editor'|'reviewer'|'viewer';
export type CreatorReviewStatus='draft'|'in_review'|'approved'|'changes_requested';
export interface CreatorSchedule { articleSlug:string; publishAt?:string; unpublishAt?:string; timezone:string; state:'draft'|'scheduled'|'published'|'unpublished'; updatedAt:string; }
const iso=(v:any)=>v?.toDate?v.toDate().toISOString():(v||new Date().toISOString());
const owns=(a:any,uid:string)=>a?.author?.uid===uid||a?.originalAuthor?.uid===uid||a?.collaborators?.some((c:any)=>c.uid===uid&&['owner','editor'].includes(c.role));
const reviews=(a:any,uid:string)=>owns(a,uid)||a?.collaborators?.some((c:any)=>c.uid===uid&&c.role==='reviewer');
export async function getCreatorCollaborators(slug:string){const s=await getDoc(doc(db,'articles',slug));if(!s.exists())throw new Error('Article not found.');return Array.isArray(s.data()?.collaborators)?s.data().collaborators:[];}
export async function inviteCreatorCollaborator(slug:string,invitee:{uid:string;username?:string},role:CreatorCollaboratorRole){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const s=await getDoc(doc(db,'articles',slug));if(!s.exists()||!owns(s.data(),uid))throw new Error('You cannot manage collaborators.');if(invitee.uid===uid)throw new Error('You are already the owner.');const ref=doc(collection(db,'collaboratorInvites'));await setDoc(ref,{articleSlug:slug,inviterId:uid,inviteeId:invitee.uid,inviteeUsername:invitee.username||'',role,status:'pending',createdAt:serverTimestamp()});}
export async function getCreatorCollaboratorInvites(){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const snap=await getDocs(query(collection(db,'collaboratorInvites'),where('inviteeId','==',uid),where('status','==','pending'),limit(50)));return snap.docs.map(d=>({id:d.id,...d.data()}));}
export async function acceptCreatorCollaboratorInvite(id:string){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'collaboratorInvites',id);const s=await getDoc(ref);if(!s.exists()||s.data()?.inviteeId!==uid||s.data()?.status!=='pending')throw new Error('Invitation is no longer valid.');const slug=String(s.data()?.articleSlug||'');const article=await getDoc(doc(db,'articles',slug));if(!article.exists())throw new Error('Article not found.');const collaborators=Array.isArray(article.data()?.collaborators)?article.data().collaborators:[];if(!collaborators.some((c:any)=>c.uid===uid))collaborators.push({uid,username:s.data()?.inviteeUsername||'',role:s.data()?.role||'viewer'});await updateDoc(article.ref,{collaborators,updatedAt:serverTimestamp()});await updateDoc(ref,{status:'accepted',respondedAt:serverTimestamp()});}
export async function declineCreatorCollaboratorInvite(id:string){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'collaboratorInvites',id);const s=await getDoc(ref);if(!s.exists()||s.data()?.inviteeId!==uid||s.data()?.status!=='pending')throw new Error('Invitation is no longer valid.');await updateDoc(ref,{status:'declined',respondedAt:serverTimestamp()});}
export async function removeCreatorCollaborator(slug:string,uidToRemove:string){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',slug);const s=await getDoc(ref);if(!s.exists()||!owns(s.data(),uid))throw new Error('You cannot manage collaborators.');if(s.data()?.author?.uid===uidToRemove)throw new Error('Owner cannot be removed.');const current=Array.isArray(s.data()?.collaborators)?s.data().collaborators:[];await updateDoc(ref,{collaborators:current.filter((c:any)=>c.uid!==uidToRemove),updatedAt:serverTimestamp()});}
export async function setCreatorReviewStatus(slug:string,status:CreatorReviewStatus,reviewNote=''){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',slug);const s=await getDoc(ref);if(!s.exists()||!reviews(s.data(),uid))throw new Error('You cannot review this content.');await updateDoc(ref,{creatorReviewStatus:status,creatorReviewNote:reviewNote.slice(0,2000),creatorReviewUpdatedBy:uid,creatorReviewUpdatedAt:serverTimestamp(),updatedAt:serverTimestamp()});}
export async function getCreatorSchedule(slug:string){const s=await getDoc(doc(db,'articles',slug,'workflow','schedule'));return s.exists()?({...s.data(),articleSlug:slug,updatedAt:iso(s.data()?.updatedAt)} as CreatorSchedule):null;}
export async function scheduleArticle(article:Article,input:{publishAt?:string;unpublishAt?:string;timezone?:string}){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!owns(s.data(),uid))throw new Error('You cannot schedule this content.');if(input.publishAt&&Date.parse(input.publishAt)<=Date.now())throw new Error('Publish time must be in the future.');if(input.unpublishAt&&input.publishAt&&Date.parse(input.unpublishAt)<=Date.parse(input.publishAt))throw new Error('Unpublish time must be after publish time.');const timezone=input.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';const state=input.publishAt?'scheduled':(s.data()?.isPublished===false?'unpublished':'published');const schedule={articleSlug:article.slug,publishAt:input.publishAt,unpublishAt:input.unpublishAt,timezone,state,updatedAt:new Date().toISOString()};await setDoc(doc(db,'articles',article.slug,'workflow','schedule'),{...schedule,createdBy:uid,updatedAt:serverTimestamp(),lastError:null},{merge:true});await updateDoc(ref,{publicationWorkflowState:state,scheduledAt:input.publishAt||null,scheduledUnpublishAt:input.unpublishAt||null,scheduledTimezone:timezone,updatedAt:serverTimestamp()});return schedule;}
export async function cancelArticleSchedule(article:Article){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!owns(s.data(),uid))throw new Error('You cannot change this schedule.');await deleteDoc(doc(db,'articles',article.slug,'workflow','schedule')).catch(()=>{});await updateDoc(ref,{publicationWorkflowState:article.isPublished===false?'unpublished':'published',scheduledAt:null,scheduledUnpublishAt:null,updatedAt:serverTimestamp()});}
export async function publishNow(article:Article){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!owns(s.data(),uid))throw new Error('You cannot publish this content.');await updateDoc(ref,{isPublished:true,mainPublicationStatus:'published',publicationWorkflowState:'published',publishedAt:serverTimestamp(),scheduledAt:null,scheduledUnpublishAt:null,updatedAt:serverTimestamp()});await deleteDoc(doc(db,'articles',article.slug,'workflow','schedule')).catch(()=>{});}
export async function unpublishNow(article:Article){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!owns(s.data(),uid))throw new Error('You cannot unpublish this content.');await updateDoc(ref,{isPublished:false,mainPublicationStatus:'unpublished',publicationWorkflowState:'unpublished',scheduledUnpublishAt:null,updatedAt:serverTimestamp()});}
