import { db, auth } from './firebase';
import { collection, doc, setDoc, getDoc, getDocs, updateDoc, deleteDoc, serverTimestamp, query, where, limit, runTransaction, writeBatch } from 'firebase/firestore';
import type { Article } from '../types';
export type CreatorCollaboratorRole='owner'|'editor'|'reviewer'|'viewer';
export type CreatorReviewStatus='draft'|'in_review'|'approved'|'changes_requested';
export interface CreatorSchedule { articleSlug:string; publishAt?:string; unpublishAt?:string; timezone:string; state:'draft'|'scheduled'|'published'|'unpublished'; updatedAt:string; }
const iso=(v:any)=>v?.toDate?v.toDate().toISOString():(v||new Date().toISOString());
const notifyUser=async(uid:string,data:any)=>{if(!uid||uid===data.actorId)return;try{await setDoc(doc(db,'users',uid,'notifications',`creator_${Date.now()}_${Math.random().toString(36).slice(2)}`),{...data,read:false,createdAt:serverTimestamp()});}catch(error){void error;}}; const ownerOf=(a:any,uid:string)=>a?.author?.uid===uid||a?.originalAuthor?.uid===uid; const arrayRole=(a:any,uid:string)=>Array.isArray(a?.collaborators)?a.collaborators.find((c:any)=>c?.uid===uid)?.role:null; const owns=(a:any,uid:string)=>ownerOf(a,uid)||['owner','editor'].includes(String(arrayRole(a,uid)||'')); const reviews=(a:any,uid:string)=>ownerOf(a,uid)||['owner','editor','reviewer'].includes(String(arrayRole(a,uid)||'')); const canPublish=(a:any,uid:string)=>ownerOf(a,uid)||Array.isArray(a?.collaborators)&&a.collaborators.some((c:any)=>c?.uid===uid&&c?.role==='editor'&&c?.canPublish===true); const collaboratorRef=(slug:string,uid:string)=>doc(db,'articles',slug,'collaborators',uid);
export async function getCreatorCollaborators(slug:string){const s=await getDoc(doc(db,'articles',slug));if(!s.exists())throw new Error('Article not found.');return Array.isArray(s.data()?.collaborators)?s.data().collaborators:[];}
export async function inviteCreatorCollaborator(slug:string,invitee:{uid:string;username?:string},role:CreatorCollaboratorRole){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const s=await getDoc(doc(db,'articles',slug));if(!s.exists()||!ownerOf(s.data(),uid))throw new Error('Only the owner can manage collaborators.');if(invitee.uid===uid)throw new Error('You are already the owner.');if(!['editor','reviewer','viewer'].includes(role))throw new Error('Invalid collaborator role.');if(!(await getDoc(doc(db,'users',invitee.uid))).exists())throw new Error('Collaborator account not found.');const ref=doc(db,'collaboratorInvites',`${slug}__${invitee.uid}`);const old=await getDoc(ref);if(old.exists()&&old.data()?.status==='pending')throw new Error('A pending invitation already exists.');await setDoc(ref,{articleSlug:slug,inviterId:uid,inviteeId:invitee.uid,inviteeUsername:invitee.username||'',role,status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});void notifyUser(invitee.uid,{type:'creator_collaborator_invitation',actorId:uid,actorUsername:'',actorName:'Creator collaboration',message:`You were invited as ${role} on ${s.data()?.title||slug}.`,targetType:'profile',targetId:slug}).catch(()=>{});}
export async function getCreatorCollaboratorInvites(){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const snap=await getDocs(query(collection(db,'collaboratorInvites'),where('inviteeId','==',uid),where('status','==','pending'),limit(50)));return snap.docs.map(d=>({id:d.id,...d.data()}));}
export async function acceptCreatorCollaboratorInvite(id:string){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'collaboratorInvites',id);await runTransaction(db,async tx=>{const inv=await tx.get(ref);if(!inv.exists()||inv.data()?.inviteeId!==uid||inv.data()?.status!=='pending')throw new Error('Invitation is no longer valid.');const slug=String(inv.data()?.articleSlug||'');const articleRef=doc(db,'articles',slug);const article=await tx.get(articleRef);if(!article.exists())throw new Error('Article not found.');const current=Array.isArray(article.data()?.collaborators)?article.data().collaborators:[];const next=current.filter((c:any)=>c?.uid!==uid).concat([{uid,username:inv.data()?.inviteeUsername||'',role:String(inv.data()?.role||'viewer'),canPublish:false}]);tx.set(collaboratorRef(slug,uid),{uid,username:inv.data()?.inviteeUsername||'',role:String(inv.data()?.role||'viewer'),canPublish:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});tx.update(articleRef,{collaborators:next,updatedAt:serverTimestamp()});tx.update(ref,{status:'accepted',respondedAt:serverTimestamp(),updatedAt:serverTimestamp()});});}
export async function declineCreatorCollaboratorInvite(id:string){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'collaboratorInvites',id);const s=await getDoc(ref);if(!s.exists()||s.data()?.inviteeId!==uid||s.data()?.status!=='pending')throw new Error('Invitation is no longer valid.');await updateDoc(ref,{status:'declined',respondedAt:serverTimestamp()});}
export async function removeCreatorCollaborator(slug:string,uidToRemove:string){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',slug);const s=await getDoc(ref);if(!s.exists()||!ownerOf(s.data(),uid))throw new Error('Only the owner can manage collaborators.');if(ownerOf(s.data(),uidToRemove))throw new Error('Owner cannot be removed.');const current=Array.isArray(s.data()?.collaborators)?s.data().collaborators:[];const batch=writeBatch(db);batch.update(ref,{collaborators:current.filter((c:any)=>c?.uid!==uidToRemove),updatedAt:serverTimestamp()});batch.delete(collaboratorRef(slug,uidToRemove));await batch.commit();}
export async function setCreatorReviewStatus(slug:string,status:CreatorReviewStatus,reviewNote=''){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',slug);const s=await getDoc(ref);if(!s.exists()||!reviews(s.data(),uid))throw new Error('You cannot review this content.');await updateDoc(ref,{creatorReviewStatus:status,creatorReviewNote:reviewNote.slice(0,2000),creatorReviewUpdatedBy:uid,creatorReviewUpdatedAt:serverTimestamp(),updatedAt:serverTimestamp()});}
export async function getCreatorSchedule(slug:string){const s=await getDoc(doc(db,'articles',slug,'workflow','schedule'));return s.exists()?({...s.data(),articleSlug:slug,updatedAt:iso(s.data()?.updatedAt)} as CreatorSchedule):null;}
export async function scheduleArticle(article:Article,input:{publishAt?:string;unpublishAt?:string;timezone?:string}){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!canPublish(s.data(),uid))throw new Error('You do not have publishing permission for this content.');if(input.publishAt&&Date.parse(input.publishAt)<=Date.now())throw new Error('Publish time must be in the future.');if(input.unpublishAt&&input.publishAt&&Date.parse(input.unpublishAt)<=Date.parse(input.publishAt))throw new Error('Unpublish time must be after publish time.');const timezone=input.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';const state=input.publishAt?'scheduled':(s.data()?.isPublished===false?'unpublished':'published');const schedule={articleSlug:article.slug,publishAt:input.publishAt,unpublishAt:input.unpublishAt,timezone,state,updatedAt:new Date().toISOString()};await setDoc(doc(db,'articles',article.slug,'workflow','schedule'),{...schedule,createdBy:uid,updatedAt:serverTimestamp(),lastError:null},{merge:true});await updateDoc(ref,{publicationWorkflowState:state,scheduledAt:input.publishAt||null,scheduledUnpublishAt:input.unpublishAt||null,scheduledTimezone:timezone,updatedAt:serverTimestamp()});return schedule;}
export async function cancelArticleSchedule(article:Article){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!canPublish(s.data(),uid))throw new Error('You cannot change this schedule.');await deleteDoc(doc(db,'articles',article.slug,'workflow','schedule')).catch(()=>{});await updateDoc(ref,{publicationWorkflowState:article.isPublished===false?'unpublished':'published',scheduledAt:null,scheduledUnpublishAt:null,updatedAt:serverTimestamp()});}
export async function publishNow(article:Article){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!canPublish(s.data(),uid))throw new Error('You do not have publishing permission for this content.');await updateDoc(ref,{isPublished:true,mainPublicationStatus:'published',publicationWorkflowState:'published',publishedAt:serverTimestamp(),scheduledAt:null,scheduledUnpublishAt:null,updatedAt:serverTimestamp()});await deleteDoc(doc(db,'articles',article.slug,'workflow','schedule')).catch(()=>{});}
export async function unpublishNow(article:Article){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',article.slug);const s=await getDoc(ref);if(!s.exists()||!canPublish(s.data(),uid))throw new Error('You do not have publishing permission for this content.');await updateDoc(ref,{isPublished:false,mainPublicationStatus:'unpublished',publicationWorkflowState:'unpublished',scheduledUnpublishAt:null,updatedAt:serverTimestamp()});}

export async function setCollaboratorPublishPermission(slug:string,collaboratorUid:string,enabled:boolean){const uid=auth.currentUser?.uid;if(!uid)throw new Error('Sign in required.');const ref=doc(db,'articles',slug);const snap=await getDoc(ref);if(!snap.exists()||!ownerOf(snap.data(),uid))throw new Error('Only the owner can change publishing permission.');const cRef=collaboratorRef(slug,collaboratorUid);const cSnap=await getDoc(cRef);if(!cSnap.exists())throw new Error('Collaborator not found.');await updateDoc(cRef,{canPublish:Boolean(enabled),updatedAt:serverTimestamp()});const current=Array.isArray(snap.data()?.collaborators)?snap.data().collaborators:[];await updateDoc(ref,{collaborators:current.map((c:any)=>c?.uid===collaboratorUid?{...c,canPublish:Boolean(enabled)}:c),updatedAt:serverTimestamp()});}
