import { db, auth } from './firebase';
import { collection, doc, getDoc, getDocs, query, orderBy, where, limit, setDoc, updateDoc, deleteDoc, writeBatch, serverTimestamp, onSnapshot, increment } from 'firebase/firestore';
import { CommunityUser } from '../types';

const id = () => Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
const date = (v:any) => v?.toDate ? v.toDate().toISOString() : (v || new Date().toISOString());
const map = (d:any) => ({ ...d.data(), id:d.id, createdAt:date(d.data().createdAt), updatedAt:date(d.data().updatedAt) });

async function profile(uid:string){ const s=await getDoc(doc(db,'users',uid)); return s.exists()?s.data() as CommunityUser:null; }
async function notify(uid:string, data:any){ if(!uid || uid===data.actorId) return; await setDoc(doc(db,'users',uid,'notifications',id()),{...data,read:false,createdAt:serverTimestamp()}); }

export interface SocialCommunity { id:string; name:string; slug:string; description:string; iconUrl?:string; bannerUrl?:string; rules?:string[]; membersCount:number; postsCount:number; ownerId:string; createdAt:string; }
export interface CommunityFeedPost { id:string; communityId:string; title:string; content:string; authorId:string; authorUsername:string; authorName:string; authorAvatar:string; score:number; commentsCount:number; createdAt:string; }
export interface SocialQuestion { id:string; title:string; details:string; authorId:string; authorUsername:string; authorName:string; authorAvatar:string; topics:string[]; followersCount:number; answersCount:number; upvotesCount:number; bestAnswerId?:string; createdAt:string; }
export interface SocialAnswer { id:string; questionId:string; content:string; authorId:string; authorUsername:string; authorName:string; authorAvatar:string; upvotesCount:number; downvotesCount:number; isBest:boolean; createdAt:string; updatedAt:string; }
export interface SocialTopic { id:string; name:string; slug:string; description:string; followersCount:number; createdAt:string; }
export interface SocialMessage { id:string; senderId:string; senderUsername:string; senderName:string; senderAvatar:string; recipientId:string; content:string; read:boolean; createdAt:string; }

export async function getCommunities():Promise<SocialCommunity[]> { const s=await getDocs(query(collection(db,'communities'),orderBy('membersCount','desc'),limit(100))); return s.docs.map(map) as SocialCommunity[]; }
export async function createCommunity(user:CommunityUser,name:string,description:string,rules:string[]=[]):Promise<SocialCommunity>{ const clean=name.trim().slice(0,60); if(!clean) throw new Error('Community name is required'); const cid=id(); const slug=clean.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||cid; const data={name:clean,slug,description:description.trim().slice(0,500),rules:rules.slice(0,20),membersCount:1,postsCount:0,ownerId:user.uid,createdAt:serverTimestamp()}; const b=writeBatch(db); b.set(doc(db,'communities',cid),data); b.set(doc(db,'communities',cid,'members',user.uid),{uid:user.uid,username:user.username,role:'owner',createdAt:serverTimestamp()}); await b.commit(); return {...data,id:cid,createdAt:new Date().toISOString()} as SocialCommunity; }
export async function isCommunityMember(cid:string,uid:string){ return (await getDoc(doc(db,'communities',cid,'members',uid))).exists(); }
export async function joinCommunity(cid:string,user:CommunityUser){ const ref=doc(db,'communities',cid,'members',user.uid); if((await getDoc(ref)).exists()) return false; const b=writeBatch(db); b.set(ref,{uid:user.uid,username:user.username,role:'member',createdAt:serverTimestamp()}); b.update(doc(db,'communities',cid),{membersCount:increment(1)}); await b.commit(); return true; }
export async function leaveCommunity(cid:string,uid:string){ const ref=doc(db,'communities',cid,'members',uid); if(!(await getDoc(ref)).exists()) return false; const c=await getDoc(doc(db,'communities',cid)); if(c.exists()&&c.data().ownerId===uid) throw new Error('Community owner cannot leave. Transfer ownership first.'); const b=writeBatch(db); b.delete(ref); b.update(doc(db,'communities',cid),{membersCount:increment(-1)}); await b.commit(); return true; }
export async function getCommunityPosts(cid:string){ const s=await getDocs(query(collection(db,'communities',cid,'posts'),orderBy('createdAt','desc'),limit(100))); return s.docs.map(map) as CommunityFeedPost[]; }
export function subscribeCommunityFeed(cid:string,cb:(x:CommunityFeedPost[])=>void){ return onSnapshot(query(collection(db,'communities',cid,'posts'),orderBy('createdAt','desc'),limit(100)),s=>cb(s.docs.map(map) as CommunityFeedPost[]),()=>cb([])); }
export async function createCommunityPost(cid:string,user:CommunityUser,title:string,content:string){ if(!(await isCommunityMember(cid,user.uid))) throw new Error('Join the community first.'); const pid=id(); const data={communityId:cid,title:title.trim().slice(0,256),content:content.trim().slice(0,100000),authorId:user.uid,authorUsername:user.username,authorName:user.displayName,authorAvatar:user.photoURL||'',score:0,commentsCount:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}; const b=writeBatch(db); b.set(doc(db,'communities',cid,'posts',pid),data); b.update(doc(db,'communities',cid),{postsCount:increment(1)}); await b.commit(); return {...data,id:pid,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()} as CommunityFeedPost; }

export async function getQuestions(){ const s=await getDocs(query(collection(db,'questions'),orderBy('createdAt','desc'),limit(100))); return s.docs.map(map) as SocialQuestion[]; }
export async function createQuestion(user:CommunityUser,title:string,details:string,topics:string[]){ const qid=id(); const data={title:title.trim().slice(0,256),details:details.trim().slice(0,100000),authorId:user.uid,authorUsername:user.username,authorName:user.displayName,authorAvatar:user.photoURL||'',topics:topics.map(x=>x.toLowerCase().trim()).filter(Boolean).slice(0,10),followersCount:0,answersCount:0,upvotesCount:0,createdAt:serverTimestamp()}; await setDoc(doc(db,'questions',qid),data); return {...data,id:qid,createdAt:new Date().toISOString()} as SocialQuestion; }
export async function getAnswers(qid:string){ const s=await getDocs(query(collection(db,'questions',qid,'answers'),orderBy('upvotesCount','desc'),limit(100))); return s.docs.map(map) as SocialAnswer[]; }
export async function createAnswer(qid:string,user:CommunityUser,content:string){ const aid=id(); const data={questionId:qid,content:content.trim().slice(0,100000),authorId:user.uid,authorUsername:user.username,authorName:user.displayName,authorAvatar:user.photoURL||'',upvotesCount:0,downvotesCount:0,isBest:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}; const b=writeBatch(db); b.set(doc(db,'questions',qid,'answers',aid),data); b.update(doc(db,'questions',qid),{answersCount:increment(1)}); await b.commit(); const q=await getDoc(doc(db,'questions',qid)); if(q.exists()) await notify(q.data().authorId,{type:'reply',actorId:user.uid,actorUsername:user.username,actorName:user.displayName,actorAvatar:user.photoURL||'',message:'answered your question',targetType:'question',targetId:qid}); return {...data,id:aid,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()} as SocialAnswer; }
export async function markBestAnswer(qid:string,aid:string,uid:string){ const q=await getDoc(doc(db,'questions',qid)); if(!q.exists()||q.data().authorId!==uid) throw new Error('Only the question author can choose the best answer.'); const answers=await getDocs(collection(db,'questions',qid,'answers')); const b=writeBatch(db); answers.docs.forEach(d=>b.update(d.ref,{isBest:d.id===aid})); b.update(q.ref,{bestAnswerId:aid}); await b.commit(); const a=await getDoc(doc(db,'questions',qid,'answers',aid)); if(a.exists()) await notify(a.data().authorId,{type:'reply',actorId:uid,actorUsername:(await profile(uid))?.username||'',actorName:(await profile(uid))?.displayName||'',message:'marked your answer as the best answer',targetType:'question',targetId:qid}); }
export async function voteAnswer(qid:string,aid:string,uid:string,type:'up'|'down'){ const ref=doc(db,'questions',qid,'votes',uid); const existing=await getDoc(ref); const b=writeBatch(db); const aRef=doc(db,'questions',qid,'answers',aid); if(existing.exists()&&existing.data().type===type){b.delete(ref);b.update(aRef,{[type==='up'?'upvotesCount':'downvotesCount']:increment(-1)});} else { const prev=existing.exists()?existing.data().type:null; b.set(ref,{type,answerId:aid,createdAt:serverTimestamp()}); b.update(aRef,{[type==='up'?'upvotesCount':'downvotesCount']:increment(1),...(prev?{[prev==='up'?'upvotesCount':'downvotesCount']:increment(-1)}:{})}); } await b.commit(); }

export async function getTopics(){ const s=await getDocs(query(collection(db,'topics'),orderBy('followersCount','desc'),limit(100))); return s.docs.map(map) as SocialTopic[]; }
export async function createTopic(user:CommunityUser,name:string,description:string){ const clean=name.trim(); const slug=clean.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,50); const existing=await getDocs(query(collection(db,'topics'),where('slug','==',slug),limit(1))); if(!existing.empty) return existing.docs[0].id; const tid=id(); await setDoc(doc(db,'topics',tid),{name:clean.slice(0,80),slug,description:description.trim().slice(0,300),followersCount:0,createdAt:serverTimestamp(),createdBy:user.uid}); return tid; }
export async function toggleTopicFollow(topicId:string,user:CommunityUser){ const ref=doc(db,'topics',topicId,'followers',user.uid); const exists=await getDoc(ref); const b=writeBatch(db); b.update(doc(db,'topics',topicId),{followersCount:increment(exists.exists()?-1:1)}); if(exists.exists()) b.delete(ref); else b.set(ref,{uid:user.uid,username:user.username,createdAt:serverTimestamp()}); await b.commit(); return !exists.exists(); }

export async function getMessages(uid:string,otherUid:string){ const a=await getDocs(query(collection(db,'messages'),where('participants','array-contains',uid),limit(200))); return a.docs.map(map).filter((m:any)=>m.senderId===otherUid||m.recipientId===otherUid) as SocialMessage[]; }
export async function sendMessage(user:CommunityUser,recipient:CommunityUser,content:string){ const text=content.trim().slice(0,5000); if(!text) return; const mid=id(); await setDoc(doc(db,'messages',mid),{senderId:user.uid,senderUsername:user.username,senderName:user.displayName,senderAvatar:user.photoURL||'',recipientId:recipient.uid,content:text,read:false,participants:[user.uid,recipient.uid],createdAt:serverTimestamp()}); await notify(recipient.uid,{type:'message',actorId:user.uid,actorUsername:user.username,actorName:user.displayName,actorAvatar:user.photoURL||'',message:'sent you a message',targetType:'profile',targetId:user.username}); }
export function subscribeMessages(uid:string,cb:(m:SocialMessage[])=>void){ return onSnapshot(query(collection(db,'messages'),where('participants','array-contains',uid),limit(200)),s=>cb(s.docs.map(map) as SocialMessage[]),()=>cb([])); }

export async function reportContent(user:CommunityUser,targetType:string,targetId:string,reason:string){ const rid=id(); await setDoc(doc(db,'reports',rid),{reporterId:user.uid,reporterUsername:user.username,targetType,targetId,reason:reason.slice(0,500),status:'open',createdAt:serverTimestamp()}); }
export async function muteUser(uid:string,targetUid:string){ await setDoc(doc(db,'users',uid,'mutes',targetUid),{uid:targetUid,createdAt:serverTimestamp()}); }
export async function unmuteUser(uid:string,targetUid:string){ await deleteDoc(doc(db,'users',uid,'mutes',targetUid)); }
export async function getUserMutes(uid:string){ const s=await getDocs(collection(db,'users',uid,'mutes')); return s.docs.map(d=>d.id); }
