import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,BookOpen,MessageCircle,Users,Heart,TrendingDown,Clock,Share2,Bookmark,Eye,GitCompare,Copy,RotateCcw} from 'lucide-react';
import type {Article,CommunityUser,PageView,Series} from '../types';
import {collection,getCountFromServer,getDocs,query,where} from 'firebase/firestore';
import {db} from '../lib/firebase';
import {getArticleAnalyticsAggregate,ArticleAnalyticsAggregate} from '../lib/analytics';
import {getSeriesList} from '../lib/series';
import {getSeriesArticles} from '../lib/cms';
import {createArticleRevision,getArticleRevisions,restoreArticleRevision} from '../lib/cms';
import {notifyToast} from '../lib/toast';

interface Props{articles:Article[];userProfile:CommunityUser|null;onNavigate:(page:PageView,param?:string)=>void}
const published=(a:Article)=>a.isPublished!==false&&a.mainPublicationStatus!=='unpublished';
const timeLabel=(ms:number)=>{const s=Math.round(ms/1000);if(s<60)return `${s}s`;return `${Math.floor(s/60)}m ${s%60}s`};

export const CreatorDashboardView:React.FC<Props>=({articles,userProfile,onNavigate})=>{
 const mine=useMemo(()=>articles.filter(a=>published(a)&&((a.author?.uid&&a.author.uid===userProfile?.uid)||(a.author?.username&&a.author.username===userProfile?.username))),[articles,userProfile?.uid,userProfile?.username]);
 const [stats,setStats]=useState<Record<string,ArticleAnalyticsAggregate>>({}); const [series,setSeries]=useState<Series[]>([]); const [selected,setSelected]=useState<string|null>(null); const [seriesBusy,setSeriesBusy]=useState(false); const [seriesData,setSeriesData]=useState<Array<{article:Article;views:number;drop:number}>>([]); const [revisions,setRevisions]=useState<any[]>([]);
 useEffect(()=>{let dead=false;Promise.all(mine.map(async a=>{const x=await getArticleAnalyticsAggregate(a.slug,Number(a.viewsCount||0));let comments=0;try{comments=(await getCountFromServer(collection(db,'articles',a.slug,'comments'))).data().count}catch{};return [a.slug,{...x,comments}] as const})).then(rows=>!dead&&setStats(Object.fromEntries(rows)));return()=>{dead=true}},[mine.map(a=>a.slug).join('|')]);
 useEffect(()=>{getSeriesList(100).then(s=>setSeries(s.filter(x=>x.ownerId===userProfile?.uid||x.ownerUsername===userProfile?.username))).catch(()=>setSeries([]))},[userProfile?.uid,userProfile?.username]);
 const totals=useMemo(()=>{const rows=mine.map(a=>stats[a.slug]);return {views:rows.reduce((n,x)=>n+(x?.views||0),0),unique:rows.reduce((n,x)=>n+(x?.uniqueReaders||0),0),reactions:rows.reduce((n,x)=>n+(x?.reactions||0),0),comments:rows.reduce((n,x)=>n+(x?.comments||0),0),shares:rows.reduce((n,x)=>n+(x?.shares||0),0)}},[mine,stats]);
 const top=useMemo(()=>[...mine].sort((a,b)=>(stats[b.slug]?.views||Number(b.viewsCount||0))-(stats[a.slug]?.views||Number(a.viewsCount||0)))[0],[mine,stats]);
 const openSeries=async(id:string)=>{setSelected(id);setSeriesBusy(true);try{const sa=await getSeriesArticles(id);const rows=[];for(const a of sa){const x=await getArticleAnalyticsAggregate(a.slug,Number(a.viewsCount||0));rows.push({article:a,views:x.views,drop:0})}for(let i=0;i<rows.length;i++)rows[i].drop=i?Math.max(0,rows[i-1].views-rows[i].views):0;setSeriesData(rows)}catch{setSeriesData([])}finally{setSeriesBusy(false)}};
 const openRevisions=async(a:Article)=>{try{const r=await getArticleRevisions(a.slug);setSelected(`rev:${a.slug}`);setRevisions(r)}catch{setRevisions([])}};
 const restore=async(id:string)=>{try{await restoreArticleRevision(id);notifyToast('Revision restored to Firestore. Reload the article to see the restored content.','success');}catch(e:any){notifyToast(e?.message||'Could not restore revision.','error')}};
 if(!userProfile)return <div className="max-w-3xl mx-auto py-24 text-center font-mono text-sm">SIGN IN TO OPEN CREATOR STUDIO.</div>;
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-14 space-y-7">
  <header className="border-4 border-black bg-black text-white p-6 sm:p-9 neo-shadow-lg"><div className="font-mono text-[10px] text-[var(--color-primary)] font-black flex items-center gap-2"><BarChart3 className="w-4 h-4"/> Creator Studio</div><h1 className="font-display font-black text-4xl sm:text-6xl uppercase mt-2">Creator Dashboard</h1><p className="mt-3 max-w-3xl text-neutral-300">Cloud analytics from real article sessions, engagement events and publication data.</p></header>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['ARTICLES',mine.length,BookOpen],['VIEWS',totals.views,Eye],['UNIQUE READERS',totals.unique,Users],['REACTIONS',totals.reactions,Heart],['COMMENTS',totals.comments,MessageCircle]].map(([l,v,I]:any)=><Metric key={l} label={l} value={Number(v).toLocaleString()} icon={<I/>}/> )}</div>
  {top&&<section className="border-4 border-black bg-[var(--color-primary)] p-6 neo-shadow"><div className="font-mono text-[10px] uppercase font-black">TOP ARTICLE · {stats[top.slug]?.views||Number(top.viewsCount||0)} OPENED</div><h2 className="font-display font-black text-3xl uppercase mt-1">{top.title}</h2><div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-5">{[['UNIQUE',stats[top.slug]?.uniqueReaders||0],['AVG TIME',timeLabel(stats[top.slug]?.averageReadingTimeMs||0)],['COMPLETION',`${stats[top.slug]?.completionRate||0}%`],['SCROLL DEPTH',`${stats[top.slug]?.scrollDepth||0}%`],['SHARES',stats[top.slug]?.shares||0]].map(([l,v])=><div key={String(l)} className="border-2 border-black bg-white p-3"><div className="font-mono text-[9px]">{l}</div><div className="font-display font-black text-2xl">{v}</div></div>)}</div><button onClick={()=>onNavigate('article',top.slug)} className="mt-5 border-2 border-black bg-black text-white px-4 py-2 font-mono text-[10px] font-black uppercase">OPEN ARTICLE →</button></section>}
  {top&&stats[top.slug]&&<section className="border-4 border-black bg-white p-5"><div className="flex items-end justify-between"><div><div className="font-mono text-[9px] uppercase">Reader funnel</div><h2 className="font-display font-black text-2xl uppercase">Article analytics</h2></div><span className="font-mono text-[9px]">LAST 500 CLOUD SESSIONS</span></div><div className="space-y-3 mt-5">{[['OPENED',stats[top.slug].funnel.opened],['REACHED 25%',stats[top.slug].funnel.p25],['REACHED 50%',stats[top.slug].funnel.p50],['REACHED 75%',stats[top.slug].funnel.p75],['COMPLETED',stats[top.slug].funnel.completed]].map(([l,v]:any,i)=><div key={l}><div className="flex justify-between font-mono text-[9px] font-black uppercase"><span>{l}</span><span>{Number(v).toLocaleString()}</span></div><div className="h-4 border-2 border-black bg-neutral-100 mt-1"><div className="h-full bg-[var(--color-primary)]" style={{width:`${Math.max(2,Math.min(100,Number(v)/(stats[top.slug].funnel.opened||1)*100))}%`}}/></div></div>)}</div><div className="grid sm:grid-cols-3 gap-2 mt-5 font-mono text-[9px] uppercase"><div className="border-2 border-black p-3">BOOKMARKS {stats[top.slug].bookmarks}</div><div className="border-2 border-black p-3">COMMENTS {stats[top.slug].comments}</div><div className="border-2 border-black p-3">RETURN READERS {stats[top.slug].returnReaders}</div></div></section>}
  <section><div className="flex items-end justify-between mb-3"><h2 className="font-display font-black text-3xl uppercase">Your Articles</h2><span className="font-mono text-[9px]">ANALYTICS + VERSION HISTORY</span></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{mine.map(a=>{const x=stats[a.slug];return <div key={a.slug} className="border-4 border-black bg-white p-4"><button onClick={()=>onNavigate('article',a.slug)} className="text-left w-full hover:bg-[var(--color-secondary)]"><div className="font-mono text-[9px] uppercase">{a.category} · {a.readingTimeMinutes||0} MIN</div><h3 className="font-display font-black text-xl uppercase mt-1">{a.title}</h3><div className="mt-4 grid grid-cols-2 gap-2 font-mono text-[9px]"><span>{x?.views??Number(a.viewsCount||0)} VIEWS</span><span>{x?.uniqueReaders??0} UNIQUE</span><span>{x?.completionRate??0}% COMPLETE</span><span>{x?.shares??0} SHARES</span></div></button><div className="flex gap-2 mt-3"><button onClick={()=>void openRevisions(a)} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black uppercase"><RotateCcw className="inline w-3 h-3"/> HISTORY</button><button onClick={async()=>{try{await createArticleRevision(a);notifyToast('Current article saved as a cloud revision.','success')}catch{}}} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black uppercase"><Copy className="inline w-3 h-3"/> SNAPSHOT</button><button onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(a,null,2));notifyToast('Article JSON duplicated to clipboard.','success')}catch{notifyToast('Could not duplicate article data.','error')}}} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black uppercase">DUPLICATE</button></div></div>})}</div></section>
  <section><div className="flex items-end justify-between mb-3"><h2 className="font-display font-black text-3xl uppercase">Series Analytics</h2><span className="font-mono text-[9px]">PART-BY-PART DROP-OFF</span></div><div className="grid md:grid-cols-2 gap-4">{series.map(s=><button key={s.id} onClick={()=>void openSeries(s.id)} className="border-4 border-black bg-white p-5 text-left hover:bg-[var(--color-secondary)]"><div className="font-mono text-[9px] uppercase">{s.articleCount||0} PARTS · {Number(s.viewsCount||0).toLocaleString()} SERIES VIEWS</div><h3 className="font-display font-black text-2xl uppercase mt-1">{s.title}</h3><div className="mt-4 flex justify-between font-mono text-[9px]"><span>OPEN ANALYTICS</span><span>→</span></div></button>)}</div></section>
  {selected?.startsWith('rev:')&&<section className="border-4 border-black bg-white p-5"><div className="flex justify-between"><h2 className="font-display font-black text-2xl uppercase">Version History</h2><button onClick={()=>setSelected(null)}>✕</button></div><div className="mt-4 space-y-2">{revisions.map((r:any)=><div key={r.id} className="border-2 border-black p-3 flex flex-wrap items-center gap-2"><div className="flex-1 font-mono text-[10px]">{r.createdAt?.toDate?.()?.toLocaleString?.()||'CLOUD REVISION'} · {r.id}</div><button onClick={()=>void restore(r.id)} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black">RESTORE</button><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(r.article||{},null,2))} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black">COMPARE / COPY</button></div>)}{!revisions.length&&<div className="font-mono text-xs">NO REVISIONS YET.</div>}</div></section>}
  {selected&&!selected.startsWith('rev:')&&<section className="border-4 border-black bg-white p-5"><div className="flex justify-between"><div><div className="font-mono text-[9px] uppercase">Series analytics</div><h2 className="font-display font-black text-2xl uppercase">{series.find(s=>s.id===selected)?.title}</h2></div><button onClick={()=>setSelected(null)}>✕</button></div>{seriesBusy?<div className="py-8 text-center font-mono text-xs">LOADING SERIES DATA…</div>:<><div className="mt-5 space-y-3">{seriesData.map((r,i)=><div key={r.article.slug} className="border-2 border-black p-3"><div className="flex justify-between font-mono text-[9px] font-black"><span>PART {String(i+1).padStart(2,'0')} · {r.article.title}</span><span>{r.views.toLocaleString()} OPENS</span></div><div className="h-3 bg-neutral-100 border-2 border-black mt-2"><div className="h-full bg-[var(--color-primary)]" style={{width:`${Math.max(2,Math.min(100, r.views/(seriesData[0]?.views||1)*100))}%`}}/></div><div className="font-mono text-[9px] mt-2">{r.drop?`DROP-OFF FROM PREVIOUS PART: ${r.drop.toLocaleString()}`:'START OF SERIES'}</div></div>)}</div></>}</section>}
 </div>
};
const Metric=({label,value,icon}:{label:string;value:string;icon:React.ReactNode})=><div className="border-2 border-black bg-white p-4"><div className="flex items-center gap-2 font-mono text-[9px] font-black uppercase">{icon}{label}</div><div className="font-display font-black text-3xl mt-2">{value}</div></div>;
