import React, { useEffect, useState } from 'react';
import { ArrowRight, Bookmark, Flame, Layers, UserPlus, Zap, CheckCircle2, Clock3 } from 'lucide-react';
import type { Article, PageView, Series } from '../types';
import { getPersonalizedHomeData, type PersonalizedHomeData } from '../lib/personalization';

interface Props { articles: Article[]; series: Series[]; userAuth: any; onNavigate: (page: PageView, param?: string) => void; }
const Section:React.FC<{label:string;title:string;children:React.ReactNode;icon?:React.ReactNode}> = ({label,title,children,icon}) => <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 border-b-4 border-black"><div className="flex items-end justify-between gap-4 mb-5"><div><div className="font-mono text-[9px] uppercase font-black flex items-center gap-2">{icon}{label}</div><h2 className="font-display font-black text-3xl uppercase tracking-tight">{title}</h2></div></div>{children}</section>;
const ArticleMini:React.FC<{a:Article;progress?:number;label?:string;onOpen:()=>void}> = ({a,progress,label,onOpen}) => <button onClick={onOpen} className="text-left border-4 border-black bg-white p-4 hover:bg-[var(--color-primary)] transition-colors"><div className="font-mono text-[9px] uppercase text-neutral-500">{label || `${a.category} · ${a.readingTimeMinutes || 0} MIN`}</div><h3 className="font-display font-black text-xl uppercase mt-1 line-clamp-2">{a.title}</h3><p className="text-sm mt-2 line-clamp-2">{a.excerpt}</p>{progress!==undefined&&<div className="mt-4"><div className="flex items-center justify-between font-mono text-[9px] font-black uppercase"><span>{progress}% complete</span><span>{Math.max(1, Math.ceil((a.readingTimeMinutes||1)*(1-progress/100)))} min left</span></div><div className="mt-1 h-2 border-2 border-black bg-white"><div className="h-full bg-[var(--color-primary)]" style={{width:`${Math.max(0,Math.min(100,progress))}%`}}/></div></div>}</button>;

export const PersonalizedHomeSections:React.FC<Props> = ({articles,series,userAuth,onNavigate}) => {
  const [data,setData]=useState<PersonalizedHomeData|null>(null);
  useEffect(()=>{let active=true;if(!userAuth?.uid){setData(null);return()=>{active=false;};} getPersonalizedHomeData(articles,series).then(x=>active&&setData(x)).catch(()=>active&&setData(null)); return()=>{active=false;};},[articles,userAuth?.uid,series]);
  if(!userAuth || !data) return null;
  const finishing = data.finishingSeries.filter(x=>x.article);
  return <>
    {data.continueSlug && <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 border-b-4 border-black"><div className="border-4 border-black bg-black text-white p-5 neo-shadow-lg flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div><div className="font-mono text-[10px] text-[var(--color-primary)] uppercase font-black flex items-center gap-2"><Clock3 className="w-4 h-4"/> Continue Reading 2.0</div><h2 className="font-display font-black text-3xl uppercase mt-1">{articles.find(a=>a.slug===data.continueSlug)?.title || data.continueSlug}</h2><p className="font-mono text-[9px] text-neutral-300 mt-2">EXACT CLOUD POSITION · CURRENT SECTION · LAST DEVICE</p></div><button onClick={()=>onNavigate('article',data.continueSlug!)} className="border-2 border-black bg-[var(--color-primary)] text-black px-5 py-3 font-mono text-[10px] font-black uppercase inline-flex items-center gap-2">RESUME <ArrowRight className="w-4 h-4"/></button></div></section>}
    {data.recommended.length>0&&<Section label="Personalized from your real activity" title="Recommended For You" icon={<Zap className="w-4 h-4"/>}><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{data.recommended.slice(0,4).map(a=><ArticleMini key={a.slug} a={a} onOpen={()=>onNavigate('article',a.slug)}/>)}</div></Section>}
    {data.followedCreatorArticles.length>0&&<Section label="Based on creators you follow" title="From Creators You Follow" icon={<UserPlus className="w-4 h-4"/>}><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{data.followedCreatorArticles.slice(0,4).map(a=><ArticleMini key={a.slug} a={a} label={`@${a.author.username || a.author.name} · ${a.readingTimeMinutes||0} MIN`} onOpen={()=>onNavigate('article',a.slug)}/>)}</div></Section>}
    {data.followedSeriesArticles.length>0&&<Section label="Based on series you follow" title="New In Your Series" icon={<Layers className="w-4 h-4"/>}><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{data.followedSeriesArticles.slice(0,4).map(a=><ArticleMini key={a.slug} a={a} label={`${a.seriesName || 'SERIES'} · PART ${a.seriesOrder || '?'}`} onOpen={()=>onNavigate('article',a.slug)}/>)}</div></Section>}
    {data.topicArticles.length>0&&<Section label="Based on your followed topics" title="New In Your Topics" icon={<Bookmark className="w-4 h-4"/>}><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{data.topicArticles.slice(0,4).map(a=><ArticleMini key={a.slug} a={a} label={`#${a.category}`} onOpen={()=>onNavigate('article',a.slug)}/>)}</div></Section>}
    {finishing.length>0&&<Section label="Cloud-synced series checkpoints" title="Finish Your Series" icon={<Layers className="w-4 h-4"/>}><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{finishing.slice(0,3).map(x=><ArticleMini key={x.article.slug} a={x.article} progress={x.progress} label={`${x.seriesName} · PART ${x.article.seriesOrder || '?'}`} onOpen={()=>onNavigate('article',x.article.slug)}/>)}</div></Section>}
    {data.trending.length>0&&<Section label="Aggregated from real engagement" title="Trending This Week" icon={<Flame className="w-4 h-4"/>}><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{data.trending.slice(0,4).map(a=><ArticleMini key={a.slug} a={a} label={`${Number(a.viewsCount||0).toLocaleString()} VIEWS · ${a.category}`} onOpen={()=>onNavigate('article',a.slug)}/>)}</div></Section>}
  </>;
};
