const FIREBASE_API_KEY = process.env.FIREBASE_WEB_API_KEY || process.env.VITE_FIREBASE_API_KEY || 'AIzaSyC1_eau-5rsMTreEzCNMtns2FGcSa448ug';
const FIREBASE_LOOKUP_URL = `https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(FIREBASE_API_KEY)}`;
const GEMINI_BASE='https://generativelanguage.googleapis.com/v1beta';
function text(value: unknown, max: number) { return String(value ?? '').slice(0, max); }
async function verifyFirebaseIdToken(token: string) { const response=await fetch(FIREBASE_LOOKUP_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:token})}); if(!response.ok)throw new Error('INVALID_FIREBASE_TOKEN'); const data=await response.json() as any; const authUser=data.users?.[0]; if(!authUser?.localId)throw new Error('INVALID_FIREBASE_TOKEN'); return {uid:String(authUser.localId),disabled:Boolean(authUser.disabled)}; }
async function listModels(key:string){const r=await fetch(`${GEMINI_BASE}/models?pageSize=1000`,{headers:{'x-goog-api-key':key}}); const raw=await r.text(); if(!r.ok)throw Object.assign(new Error(raw.slice(0,300)),{status:r.status}); const d=JSON.parse(raw); const names=(d.models||[]).filter((m:any)=>Array.isArray(m.supportedGenerationMethods)&&m.supportedGenerationMethods.includes('generateContent')).map((m:any)=>String(m.name||'').replace(/^models\//,'')); return names;}
async function generate(key:string,prompt:string){const names=await listModels(key); const model=[process.env.GEMINI_MODEL||'gemini-3.7-flash','gemini-3.5-flash','gemini-3.1-flash-lite','gemini-2.5-flash','gemini-2.5-flash-lite'].find(x=>names.includes(x))||names.find((x:string)=>/flash/i.test(x)); if(!model)throw Object.assign(new Error('NO_GEMINI_MODEL'),{status:404}); const r=await fetch(`${GEMINI_BASE}/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:0.2}})}); const raw=await r.text(); if(!r.ok)throw Object.assign(new Error(raw.slice(0,600)),{status:r.status}); const d=JSON.parse(raw); return String(d?.candidates?.[0]?.content?.parts?.map((p:any)=>p?.text||'').join('')||'').trim();}
export default async function handler(req:any,res:any){
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});
 const key=String(process.env.GEMINI_API_KEY||process.env.GOOGLE_GEMINI_API_KEY||process.env.GOOGLE_API_KEY||'').trim().replace(/^['"]|['"]$/g,'');if(!key)return res.status(503).json({error:'Discussion AI is not configured.'});
 try{const authorization=String(req.headers.authorization||'');const token=authorization.startsWith('Bearer ')?authorization.slice(7).trim():'';if(!token)return res.status(401).json({error:'Authentication required.'});const verified=await verifyFirebaseIdToken(token);if(verified.disabled)return res.status(403).json({error:'Account disabled.'});const body=req.body||{};const title=text(body.title,500);const content=text(body.content,12000);const replies=Array.isArray(body.replies)?body.replies.slice(0,120).map((r:any)=>({id:text(r.id,80),author:text(r.author,80),content:text(r.content,5000),likes:Number(r.likes||0),authorResponse:Boolean(r.authorResponse)})):[];if(!title||replies.length<5)return res.status(400).json({error:'A discussion title and at least five replies are required.'});const prompt=['You are OFFSCRPT Discussion Intelligence. Analyze ONLY the supplied discussion content and replies.','Never invent facts, sources, positions, or conclusions not supported by the supplied material.','Return strict JSON with keys: overview (string), arguments (string[]), agreements (string[]), disagreements (string[]), unresolved (string[]), useful (string[]).','Keep each array concise, concrete, and grounded. Useful replies should identify actual reply IDs when possible.',`DISCUSSION TITLE:\n${title}\n\nDISCUSSION BODY:\n${content}\n\nREPLIES JSON:\n${JSON.stringify(replies)}`].join('\n');const raw=await generate(key,prompt);const parsed=JSON.parse(raw.replace(/^```json\s*/i,'').replace(/\s*```$/,''));return res.status(200).json({overview:text(parsed.overview,1800),arguments:Array.isArray(parsed.arguments)?parsed.arguments.map((x:any)=>text(x,300)).filter(Boolean).slice(0,8):[],agreements:Array.isArray(parsed.agreements)?parsed.agreements.map((x:any)=>text(x,300)).filter(Boolean).slice(0,8):[],disagreements:Array.isArray(parsed.disagreements)?parsed.disagreements.map((x:any)=>text(x,300)).filter(Boolean).slice(0,8):[],unresolved:Array.isArray(parsed.unresolved)?parsed.unresolved.map((x:any)=>text(x,300)).filter(Boolean).slice(0,8):[],useful:Array.isArray(parsed.useful)?parsed.useful.map((x:any)=>text(x,300)).filter(Boolean).slice(0,8):[]});}
 catch(error:any){console.error('discussion-summary failed',error);const status=Number(error?.status||0);if(error?.message==='INVALID_FIREBASE_TOKEN')return res.status(401).json({error:'Authentication expired. Please sign in again.'});if(status===401||status===403)return res.status(502).json({error:'Gemini rejected the configured API key.',code:'GEMINI_AUTH'});if(status===429)return res.status(429).json({error:'Gemini quota or rate limit reached.',code:'GEMINI_QUOTA'});if(status===404)return res.status(502).json({error:'No compatible Gemini model is available for this project.',code:'GEMINI_MODEL'});return res.status(502).json({error:'Discussion AI request failed. Retry after checking the Gemini configuration.',code:'GEMINI_GATEWAY'});}
}
