import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Bell, BookOpen, Bookmark, FileText, Layers, MessageCircle, Save, Sparkles } from 'lucide-react';
import { loginWithGoogle } from '../lib/firebase';
import { useAuthUser } from '../lib/useAuthUser';
import { getUnifiedAccountActivity, type AccountActivity } from '../lib/account';
import { subscribeArticleHistory, type ArticleHistoryItem } from '../lib/reading';
import type { Article, CommunityUser, PageView } from '../types';

interface Props { onNavigate:(page:PageView,param?:string)=>void; userProfile:CommunityUser|null; articles:Article[]; }
const day=(v?:string)=>{const d=v?new Date(v):new Date();const n=new Date();const x=new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();const t=new Date(n.getFullYear(),n.getMonth(),n.getDate()).getTime(); if(x===t)return'TODAY'; if(x===t-86400000)return'YESTERDAY'; return'THIS WEEK';};
const icon=(a:AccountActivity)=>a.kind==='read'?<BookOpen className="w-4 h-4"/>:a.kind==='saved'?<Bookmark className="w-4 h-4"/>:<Bell className="w-4 h-4"/>;
export const ActivityCenterView:React.FC<Props>=({onNavigate,userProfile,articles})=>{
 const user=useAuthUser(); const [items,setItems]=useState<AccountActivity[]>([]); const [history,setHistory]=useState<ArticleHistoryItem[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!user){setItems([]);setLoading(false);return;}let active=true;getUnifiedAccountActivity().then(x=>active&&setItems(x)).catch(()=>active&&setItems([])).finally(()=>active&&setLoading(false));const unsub=subscribeArticleHistory(h=>setHistory(h),60);return()=>{active=false;unsub();};},[user?.uid]);
 useEffect(()=>{if(user) getUnifiedAccountActivity().then(setItems).catch(()=>{});},[history,user?.uid]);
 const grouped=useMemo<Record<string,AccountActivity[]>>(()=>{const g:Record<string,AccountActivity[]>={};items.forEach(i=>{const k=day(i.at);(g[k] ||= []).push(i)});return g},[items]);
 const open=(i:AccountActivity)=>{if(i.targetType==='article'&&i.targetSlug)onNavigate('article',i.targetSlug); else if(i.targetType==='post'&&i.targetSlug)onNavigate('community_post',i.targetSlug); else if(i.targetType==='profile'&&i.targetSlug)onNavigate('community_profile',i.targetSlug);};
 if(!user)return <div className="max-w-3xl mx-auto px-4 py-24 text-center"><Activity className="w-12 h-12 mx-auto"/><h1 className="font-display font-black text-4xl uppercase mt-3">MY ACTIVITY</h1><p className="mt-3 text-neutral-600">Sign in to sync your reading, social, saved and creation activity.</p><button onClick={()=>void loginWithGoogle()} className="mt-6 border-2 border-black bg-[var(--color-primary)] px-5 py-3 font-mono text-[10px] font-black uppercase">SIGN IN WITH GOOGLE</button></div>;
 const continueItem=history.find(h=>Number(h.progress||0)>0&&Number(h.progress||0)<100);
 return <div className="max-w-5xl mx-auto px-4 sm:px-6 py-10 sm:py-14"><header className="border-4 border-black bg-[var(--color-primary)] p-6 sm:p-8 neo-shadow-lg"><div className="font-mono text-[10px] uppercase font-black flex items-center gap-2"><Activity className="w-4 h-4"/> MY OFFSCRPT / ACTIVITY</div><h1 className="font-display font-black text-4xl sm:text-6xl uppercase mt-2">Your Activity</h1><p className="mt-3 max-w-2xl">One cloud-backed timeline for reading, social activity and creation.</p></header>
 {continueItem&&<button onClick={()=>onNavigate('article',continueItem.slug)} className="w-full mt-6 border-4 border-black bg-black text-white text-left p-5 neo-shadow"><div className="font-mono text-[9px] uppercase text-[var(--color-primary)]">CONTINUE READING</div><div className="font-display font-black text-2xl uppercase mt-1">{articles.find(a=>a.slug===continueItem.slug)?.title||continueItem.title}</div><div className="font-mono text-[9px] mt-2">{Math.round(Number(continueItem.progress||0))}% · {continueItem.lastSection?'CURRENT SECTION SAVED':''} · CLOUD SYNCED</div></button>}
 {loading?<div className="py-20 text-center font-mono text-xs uppercase">SYNCING ACTIVITY…</div>:!items.length?<div className="mt-6 border-4 border-dashed border-black p-10 text-center font-mono text-sm">YOUR ACTIVITY WILL APPEAR HERE AS YOU USE OFFSCRPT.</div>:<div className="mt-8 space-y-8">{(Object.entries(grouped) as Array<[string,AccountActivity[]]>).map(([g,rows])=><section key={g}><div className="font-mono text-[10px] font-black uppercase border-b-2 border-black pb-2 mb-3">{g}</div><div className="space-y-2">{rows.map(i=><button key={i.id} onClick={()=>open(i)} className="w-full text-left border-2 border-black bg-white p-4 flex items-start gap-3 hover:bg-[var(--color-secondary)]/20"><div className="w-9 h-9 border-2 border-black grid place-items-center shrink-0 bg-[var(--color-primary)]">{icon(i)}</div><div className="min-w-0 flex-1"><div className="font-display font-black uppercase">{i.title}</div><div className="font-mono text-[10px] mt-1 text-neutral-600 uppercase">{i.subtitle}</div></div><div className="font-mono text-[9px] text-neutral-500 shrink-0">{i.at?new Date(i.at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):''}</div></button>)}</div></section>)}</div>}
 </div>
};
