import React,{useEffect,useMemo,useState} from 'react';
import {Database,Shield,RefreshCw,Trash2,Edit2,Save,RotateCcw,Download,Users,MessageSquare,FileText,Globe,Search} from 'lucide-react';
import {auth} from '../lib/firebase';
import {CommunityUser} from '../types';
import {getAllCommunityUsers} from '../lib/community';
import {getSiteConfig,createSiteConfigBackup,getSiteConfigBackups,restoreSiteConfigBackup} from '../lib/cms';
import {getAdminRootAndCommunityPosts,adminUpdateRootPost,adminUpdateCommunityPost,adminDeleteRootPost,adminDeleteCommunityPost,adminSetRootPostFeatured,adminSetCommunityPostFeatured,getAdminMessages,adminUpdateMessage,adminDeleteMessage,adminUpdateUser,adminDeleteUserProfile,getCommunities,updateCommunity,deleteCommunity,getQuestions,updateQuestion,deleteQuestion,getTopics,updateTopic,deleteTopic,getReports,resolveReport,SocialAdminPost,SocialMessage,SocialCommunity,SocialQuestion,SocialTopic,SocialReport} from '../lib/social';

interface Props{onSiteConfigRestored?:()=>Promise<void>|void;}

export const AdminControlPanel:React.FC<Props>=({onSiteConfigRestored})=>{
 const adminId=auth.currentUser?.uid||'';
 const [section,setSection]=useState<'overview'|'users'|'posts'|'messages'|'communities'|'questions'|'topics'|'reports'|'backups'>('overview');
 const [users,setUsers]=useState<CommunityUser[]>([]); const [posts,setPosts]=useState<SocialAdminPost[]>([]); const [messages,setMessages]=useState<SocialMessage[]>([]); const [communities,setCommunities]=useState<SocialCommunity[]>([]); const [questions,setQuestions]=useState<SocialQuestion[]>([]); const [topics,setTopics]=useState<SocialTopic[]>([]); const [reports,setReports]=useState<SocialReport[]>([]); const [backups,setBackups]=useState<any[]>([]);
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [search,setSearch]=useState(''); const [editing,setEditing]=useState<any|null>(null); const [editTitle,setEditTitle]=useState(''); const [editContent,setEditContent]=useState('');
 const [backupLabel,setBackupLabel]=useState(''); const [editWebsite,setEditWebsite]=useState(''); const [editX,setEditX]=useState(''); const [editGithub,setEditGithub]=useState(''); const [editTelegram,setEditTelegram]=useState(''); const [editInstagram,setEditInstagram]=useState('');
 const load=async()=>{setBusy(true);setMessage('');const tasks=await Promise.allSettled([getAllCommunityUsers(),getAdminRootAndCommunityPosts(),getAdminMessages(),getSiteConfigBackups(),getCommunities(),getQuestions(),getTopics(),getReports()]);const [u,p,m,b,c,q,t,r]=tasks;const failed:string[]=[];if(u.status==='fulfilled')setUsers(u.value);else failed.push('users');if(p.status==='fulfilled')setPosts(p.value);else failed.push('posts');if(m.status==='fulfilled')setMessages(m.value);else failed.push('messages');if(b.status==='fulfilled')setBackups(b.value);else failed.push('backups');if(c.status==='fulfilled')setCommunities(c.value);else failed.push('communities');if(q.status==='fulfilled')setQuestions(q.value);else failed.push('questions');if(t.status==='fulfilled')setTopics(t.value);else failed.push('topics');if(r.status==='fulfilled')setReports(r.value);else failed.push('reports');if(failed.length)setMessage('Some cloud sections could not load: '+failed.join(', '));setBusy(false)};
 useEffect(()=>{load()},[]);
 const filteredUsers=useMemo(()=>users.filter(u=>{const q=search.trim().toLowerCase().replace(/^@/,'');return !q||u.username.toLowerCase().includes(q)||(u.displayName||'').toLowerCase().includes(q)}),[users,search]);
 const filteredPosts=useMemo(()=>posts.filter(p=>{const q=search.trim().toLowerCase();return !q||p.title.toLowerCase().includes(q)||p.content.toLowerCase().includes(q)||p.authorUsername.toLowerCase().includes(q)}),[posts,search]);
 const filteredMessages=useMemo(()=>messages.filter(m=>{const q=search.trim().toLowerCase();return !q||m.content.toLowerCase().includes(q)||m.senderUsername.toLowerCase().includes(q)||m.recipientId.toLowerCase().includes(q)}),[messages,search]);
 const startEdit=(item:any)=>{setEditing(item);setEditTitle(item.title||item.displayName||'');setEditContent(item.content||item.bio||'');setEditWebsite(item.websiteUrl||'');setEditX(item.socialX||'');setEditGithub(item.socialGithub||'');setEditTelegram(item.socialTelegram||'');setEditInstagram(item.socialInstagram||'');};
 const saveEdit=async()=>{if(!editing)return;try{if(editing.sourceType==='community') await adminUpdateCommunityPost(editing.communityId,editing.id,editTitle,editContent); else await adminUpdateRootPost(editing.id,editTitle,editContent);setEditing(null);await load();setMessage('Content updated and synced to Firestore.')}catch(e:any){setMessage(e.message||'Update failed.')}};
 const removePost=async(p:SocialAdminPost)=>{if(!window.confirm(`Delete this ${p.sourceType==='community'?'community post':'post'} permanently?`))return;try{if(p.sourceType==='community') await adminDeleteCommunityPost(p.communityId,p.id); else await adminDeleteRootPost(p.id);await load();setMessage('Post deleted and cloud state updated.')}catch(e:any){setMessage(e.message||'Delete failed.')}};
 const toggleFeature=async(p:SocialAdminPost)=>{try{if(p.sourceType==='community'){setMessage('Community posts are moderated by the community; use EDIT/DELETE controls instead.');return;}await adminSetRootPostFeatured(p.id,!p.isFeatured);await load();setMessage(p.isFeatured?'Post removed from featured.':'Post featured.')}catch(e:any){setMessage(e.message||'Feature update failed.')}};
 const saveMessage=async()=>{if(!editing)return;try{await adminUpdateMessage(editing.id,editContent);setEditing(null);await load();setMessage('Message updated.')}catch(e:any){setMessage(e.message||'Message update failed.')}};
 const removeMessage=async(m:SocialMessage)=>{if(!window.confirm('Delete this message permanently?'))return;try{await adminDeleteMessage(m.id);await load();setMessage('Message deleted.')}catch(e:any){setMessage(e.message||'Message delete failed.')}};
 const makeBackup=async()=>{try{const config=await getSiteConfig();await createSiteConfigBackup(config,backupLabel||'Manual backup');setBackupLabel('');await load();setMessage('Global settings backup created in Firestore.')}catch(e:any){setMessage(e.message||'Backup failed.')}};
 const restore=async(b:any)=>{if(!window.confirm(`Restore global settings from ${b.label||'this backup'}?`))return;try{const config=await restoreSiteConfigBackup(b.id);if(onSiteConfigRestored) await onSiteConfigRestored();setMessage(`Global settings restored from ${config?b.label:'backup'}.`);await load();}catch(e:any){setMessage(e.message||'Restore failed.')}};
 return <div className="p-6 max-h-[72vh] overflow-y-auto space-y-5">
  <div className="border-4 border-black bg-black text-white p-5"><div className="flex items-center gap-3"><Shield/><div><h3 className="font-display font-black text-2xl uppercase">MASTER CONTROL</h3><p className="font-mono text-xs text-neutral-300">Cloud-synced control over users, posts, messages and recoverable site settings.</p></div></div></div>
  {message&&<div className="border-2 border-black bg-[var(--color-primary)] p-3 font-mono text-xs font-bold">{message}</div>}
  <div className="flex flex-wrap gap-2">{([['overview','OVERVIEW',Database],['users','USERS',Users],['posts','POSTS',FileText],['messages','MESSAGES',MessageSquare],['communities','COMMUNITIES',Globe],['questions','QUESTIONS',FileText],['topics','TOPICS',Search],['reports','REPORTS',Shield],['backups','BACKUPS',RotateCcw]] as any[]).map(([v,l,I])=><button key={v} onClick={()=>{setSection(v);setSearch('')}} className={`px-3 py-2 border-2 border-black font-mono text-[10px] font-black ${section===v?'bg-[var(--color-primary)]':''}`}><I className="inline w-3 h-3 mr-1"/>{l}</button>)}</div>
  {section!=='overview'&&section!=='backups'&&<div className="flex gap-2"><Search className="w-5 h-5 mt-2"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter this section..." className="flex-1 border-2 border-black p-2 font-mono text-xs"/></div>}
  {busy?<div className="py-10 text-center font-mono text-xs"><RefreshCw className="inline animate-spin mr-2"/>SYNCING CLOUD CONTROL DATA...</div>:section==='overview'?<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3">{[['Users',users.length],['Posts',posts.length],['Messages',messages.length],['Backups',backups.length]].map(([l,n])=><div key={String(l)} className="border-4 border-black p-5 bg-white"><div className="font-mono text-[10px] font-black">{l}</div><div className="font-display font-black text-4xl mt-2">{n}</div></div>)}<div className="md:col-span-2 xl:col-span-4 border-2 border-black p-4 font-mono text-xs">Use <b>Master Control</b> for cross-site moderation. Existing article/editor controls remain in their dedicated modules. All destructive actions are explicit and reflected in Firestore.</div></div>
  :section==='users'?<div className="space-y-2">{filteredUsers.map(u=><div key={u.uid} className="border-2 border-black p-3 flex flex-wrap justify-between gap-3"><div><div className="font-display font-black">{u.displayName}</div><div className="font-mono text-[10px]">@{u.username} · {u.uid}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>{setEditing({kind:'user',...u});setEditTitle(u.displayName||'');setEditContent(u.bio||'')}} className="border-2 border-black px-2 py-2 font-mono text-[10px]"><Edit2 className="inline w-3 h-3"/> EDIT PROFILE</button><button onClick={async()=>{try{await adminUpdateUser(u.uid,{isBlocked:!u.isBlocked});await load();setMessage(u.isBlocked?'User unblocked.':'User blocked.')}catch(e:any){setMessage(e.message||'User moderation failed.')}}} className="border-2 border-black px-2 py-2 font-mono text-[10px]">{u.isBlocked?'UNBLOCK':'BLOCK'}</button><button onClick={async()=>{if(!window.confirm(`Delete the cloud profile record for @${u.username}?`))return;try{await adminDeleteUserProfile(u.uid);await load();setMessage('Profile record deleted. Firebase Authentication account remains unchanged.')}catch(e:any){setMessage(e.message||'Profile deletion failed.')}}} className="border-2 border-black bg-red-100 px-2 py-2 font-mono text-[10px]"><Trash2 className="inline w-3 h-3"/> DELETE PROFILE</button></div></div>)}{filteredUsers.length===0&&<Empty text="No users match this filter."/>}</div>
  :section==='posts'?<div className="space-y-2">{filteredPosts.map(p=><div key={`${p.sourceType}:${p.communityId||''}:${p.id}`} className="border-2 border-black p-3"><div className="flex justify-between gap-3"><div><div className="font-mono text-[10px]">{p.sourceType==='community'?`c/${p.communitySlug||p.communityId}`:'ROOT POST'} · @{p.authorUsername}</div><div className="font-display font-black text-lg">{p.title}</div><p className="text-xs mt-1 line-clamp-3">{p.content}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>startEdit(p)} className="border-2 border-black px-2 py-2 font-mono text-[10px]"><Edit2 className="inline w-3 h-3"/> EDIT</button><button onClick={()=>removePost(p)} className="border-2 border-black bg-red-100 px-2 py-2 font-mono text-[10px]"><Trash2 className="inline w-3 h-3"/> DELETE</button><button onClick={async()=>{try{if(p.sourceType==='community') await adminSetCommunityPostFeatured(p.communityId!,p.id,!p.isFeatured); else await adminSetRootPostFeatured(p.id,!p.isFeatured);await load();setMessage(p.isFeatured?'Post removed from featured.':'Post featured.')}catch(e:any){setMessage(e.message||'Feature update failed.')}}} className="border-2 border-black px-2 py-2 font-mono text-[10px]">{p.isFeatured?'UNFEATURE':'FEATURE'}</button></div></div></div>)}{filteredPosts.length===0&&<Empty text="No posts match this filter."/>}</div>
  :section==='messages'?<div className="space-y-2">{filteredMessages.map(m=><div key={m.id} className="border-2 border-black p-3 flex flex-wrap justify-between gap-3"><div><div className="font-mono text-[10px]">@{m.senderUsername} → {m.recipientId}</div><div className="text-sm mt-1 whitespace-pre-wrap">{m.content}</div><div className="font-mono text-[9px] text-neutral-500 mt-1">{m.createdAt}</div></div><div className="flex gap-2"><button onClick={()=>{setEditing(m);setEditContent(m.content)}} className="border-2 border-black px-2 py-2 font-mono text-[10px]"><Edit2 className="inline w-3 h-3"/> EDIT</button><button onClick={()=>removeMessage(m)} className="border-2 border-black bg-red-100 px-2 py-2 font-mono text-[10px]"><Trash2 className="inline w-3 h-3"/> DELETE</button></div></div>)}{filteredMessages.length===0&&<Empty text="No messages match this filter."/>}</div>
  :section==='communities'?<div className="space-y-2">{communities.filter(c=>{const q=search.toLowerCase();return !q||c.name.toLowerCase().includes(q)||c.slug.toLowerCase().includes(q)||(c.ownerUsername||'').toLowerCase().includes(q)}).map(c=><div key={c.id} className="border-2 border-black p-3 flex flex-wrap justify-between gap-3"><div><div className="font-display font-black">c/{c.slug}</div><div className="font-mono text-[10px]">BY @{c.ownerUsername||'creator'} · {c.membersCount} MEMBERS · {c.postsCount} POSTS</div><p className="text-xs mt-1">{c.description}</p></div><div className="flex gap-2"><button onClick={async()=>{const name=window.prompt('Community name',c.name);if(name===null)return;const description=window.prompt('Description',c.description);if(description===null)return;try{await updateCommunity(c.id,adminId,{name,description,rules:c.rules||[],iconUrl:c.iconUrl,bannerUrl:c.bannerUrl});await load();setMessage('Community updated.')}catch(e:any){setMessage(e.message||'Community update failed.')}}} className="border-2 border-black px-2 py-2 font-mono text-[10px]">EDIT</button><button onClick={async()=>{if(!window.confirm(`Delete c/${c.slug} permanently?`))return;try{await deleteCommunity(c.id,adminId);await load();setMessage('Community deleted everywhere.')}catch(e:any){setMessage(e.message||'Community deletion failed.')}}} className="border-2 border-black bg-red-100 px-2 py-2 font-mono text-[10px]">DELETE</button></div></div>)}</div>
  :section==='questions'?<div className="space-y-2">{questions.filter(q=>{const x=search.toLowerCase();return !x||q.title.toLowerCase().includes(x)||q.authorUsername.toLowerCase().includes(x)}).map(q=><div key={q.id} className="border-2 border-black p-3 flex justify-between gap-3"><div><div className="font-display font-black">{q.title}</div><div className="font-mono text-[10px]">@{q.authorUsername} · {q.answersCount} ANSWERS</div></div><div className="flex gap-2"><button onClick={async()=>{const title=window.prompt('Question title',q.title);if(title===null)return;const details=window.prompt('Question details',q.details);if(details===null)return;try{await updateQuestion(q.id,adminId,title,details);await load();setMessage('Question updated.')}catch(e:any){setMessage(e.message||'Question update failed.')}}} className="border-2 border-black px-2 py-2 font-mono text-[10px]">EDIT</button><button onClick={async()=>{if(!window.confirm('Delete question and its answers?'))return;try{await deleteQuestion(q.id,adminId);await load();setMessage('Question deleted.')}catch(e:any){setMessage(e.message||'Question deletion failed.')}}} className="border-2 border-black bg-red-100 px-2 py-2 font-mono text-[10px]">DELETE</button></div></div>)}</div>
  :section==='topics'?<div className="space-y-2">{topics.filter(t=>{const x=search.toLowerCase();return !x||t.name.toLowerCase().includes(x)||t.slug.toLowerCase().includes(x)||(t.creatorUsername||'').toLowerCase().includes(x)}).map(t=><div key={t.id} className="border-2 border-black p-3 flex justify-between gap-3"><div><div className="font-display font-black">#{t.slug}</div><div className="font-mono text-[10px]">BY @{t.creatorUsername||'creator'} · {t.followersCount||0} FOLLOWERS</div></div><div className="flex gap-2"><button onClick={async()=>{const name=window.prompt('Topic name',t.name);if(name===null)return;const description=window.prompt('Description',t.description);if(description===null)return;try{await updateTopic(t.id,adminId,name,description);await load();setMessage('Topic updated.')}catch(e:any){setMessage(e.message||'Topic update failed.')}}} className="border-2 border-black px-2 py-2 font-mono text-[10px]">EDIT</button><button onClick={async()=>{if(!window.confirm('Delete this topic?'))return;try{await deleteTopic(t.id,adminId);await load();setMessage('Topic deleted.')}catch(e:any){setMessage(e.message||'Topic deletion failed.')}}} className="border-2 border-black bg-red-100 px-2 py-2 font-mono text-[10px]">DELETE</button></div></div>)}</div>
  :section==='reports'?<div className="space-y-2">{reports.filter(r=>{const x=search.toLowerCase();return !x||r.reason.toLowerCase().includes(x)||r.reporterUsername?.toLowerCase().includes(x)||r.targetType.toLowerCase().includes(x)}).map(r=><div key={r.id} className="border-2 border-black p-4 space-y-2"><div className="font-mono text-[10px] font-black uppercase">{r.status} · {r.targetType} · REPORTED BY @{r.reporterUsername||'user'}</div><div className="text-sm">{r.reason}</div>{r.response&&<div className="border-2 border-black bg-neutral-100 p-2 font-mono text-xs">Response: {r.response}</div>} {r.status==='open'&&<div className="flex flex-wrap gap-2"><button onClick={async()=>{const response=window.prompt('Response to reporter','We reviewed the report and kept the content. Reason:');if(response===null)return;try{await resolveReport(r.id,adminId,'dismissed',response);await load();setMessage('Report dismissed and reporter notified.')}catch(e:any){setMessage(e.message||'Report response failed.')}}} className="border-2 border-black px-2 py-2 font-mono text-[10px]">KEEP + RESPOND</button><button onClick={async()=>{const response=window.prompt('Response to reporter','The reported content was removed because it violated site rules.');if(response===null)return;try{const [type,id2]=r.targetType==='community_post'&&r.targetId.includes(':')?r.targetId.split(':'):[r.targetType,r.targetId];if(type==='community_post'){const [cid,pid]=r.targetId.split(':');await adminDeleteCommunityPost(cid,pid);} else if(type==='post'){await adminDeleteRootPost(r.targetId);};await resolveReport(r.id,adminId,'resolved',response);await load();setMessage('Report resolved and reporter notified.')}catch(e:any){setMessage(e.message||'Report resolution failed.')}}} className="border-2 border-black bg-red-100 px-2 py-2 font-mono text-[10px]">REMOVE + RESPOND</button></div>}</div>)}</div>
  :<div className="space-y-4"><div className="border-2 border-black p-4 bg-neutral-50"><div className="font-display font-black text-xl uppercase">GLOBAL SITE SETTINGS BACKUP / RESTORE</div><p className="font-mono text-xs mt-2">Before major edits, snapshot the complete current global site configuration. Restore writes that snapshot back to <code>siteConfig/global</code>.</p><div className="flex gap-2 mt-4"><input value={backupLabel} onChange={e=>setBackupLabel(e.target.value)} placeholder="Backup label (optional)" className="flex-1 border-2 border-black p-2 font-mono text-xs"/><button onClick={makeBackup} className="border-2 border-black bg-[var(--color-primary)] px-3 py-2 font-mono text-xs font-black"><Download className="inline w-3 h-3"/> CREATE BACKUP</button></div></div>{backups.map(b=><div key={b.id} className="border-2 border-black p-4 flex flex-wrap justify-between gap-3"><div><div className="font-display font-black">{b.label||'Backup'}</div><div className="font-mono text-[10px]">{b.createdAt} · BY {b.createdByEmail||'admin'}</div></div><button onClick={()=>restore(b)} className="border-2 border-black px-3 py-2 font-mono text-[10px] font-black"><RotateCcw className="inline w-3 h-3"/> RESTORE</button></div>)}{backups.length===0&&<Empty text="No global configuration backups yet."/>}</div>}
  {editing&&<div className="fixed inset-0 z-[300] bg-black/70 p-4 grid place-items-center"><div className="bg-white border-4 border-black w-full max-w-2xl p-5 space-y-4"><div className="flex justify-between"><h3 className="font-display font-black uppercase">MASTER EDITOR</h3><button onClick={()=>setEditing(null)}>✕</button></div>{editing.kind==='user'?<><input value={editTitle} onChange={e=>setEditTitle(e.target.value)} placeholder="Display name" className="w-full border-2 border-black p-3"/><textarea value={editContent} onChange={e=>setEditContent(e.target.value)} placeholder="Bio" className="w-full border-2 border-black p-3 min-h-32"/><div className="grid sm:grid-cols-2 gap-2"><input value={editWebsite} onChange={e=>setEditWebsite(e.target.value)} placeholder="Website URL" className="border-2 border-black p-2 font-mono text-xs"/><input value={editX} onChange={e=>setEditX(e.target.value)} placeholder="X URL" className="border-2 border-black p-2 font-mono text-xs"/><input value={editGithub} onChange={e=>setEditGithub(e.target.value)} placeholder="GitHub URL" className="border-2 border-black p-2 font-mono text-xs"/><input value={editTelegram} onChange={e=>setEditTelegram(e.target.value)} placeholder="Telegram URL" className="border-2 border-black p-2 font-mono text-xs"/><input value={editInstagram} onChange={e=>setEditInstagram(e.target.value)} placeholder="Instagram URL" className="border-2 border-black p-2 font-mono text-xs sm:col-span-2"/></div><button onClick={async()=>{try{await adminUpdateUser(editing.uid,{displayName:editTitle,bio:editContent,websiteUrl:editWebsite,socialX:editX,socialGithub:editGithub,socialTelegram:editTelegram,socialInstagram:editInstagram});setEditing(null);await load();setMessage('User profile and social links updated.')}catch(e:any){setMessage(e.message||'User update failed.')}}} className="border-2 border-black bg-[var(--color-primary)] px-4 py-2 font-mono text-xs font-black"><Save className="inline w-3 h-3"/> SAVE USER</button></>:editing.senderId?<><textarea value={editContent} onChange={e=>setEditContent(e.target.value)} className="w-full border-2 border-black p-3 min-h-32"/><button onClick={saveMessage} className="border-2 border-black bg-[var(--color-primary)] px-4 py-2 font-mono text-xs font-black"><Save className="inline w-3 h-3"/> SAVE MESSAGE</button></>:<><input value={editTitle} onChange={e=>setEditTitle(e.target.value)} className="w-full border-2 border-black p-3"/><textarea value={editContent} onChange={e=>setEditContent(e.target.value)} className="w-full border-2 border-black p-3 min-h-32"/><button onClick={saveEdit} className="border-2 border-black bg-[var(--color-primary)] px-4 py-2 font-mono text-xs font-black"><Save className="inline w-3 h-3"/> SAVE CONTENT</button></>}</div></div>}
  <button onClick={load} className="border-2 border-black px-4 py-2 font-mono text-xs font-black"><RefreshCw className="inline w-4 h-4 mr-2"/>REFRESH MASTER DATA</button>
 </div>;
};
const Empty=({text}:{text:string})=><div className="border-2 border-dashed border-black p-8 text-center font-mono text-xs">{text}</div>;
