import React,{useState} from 'react';
import {Bot,Brain,Check,ChevronDown,Copy,FileQuestion,GraduationCap,Lightbulb,Loader2,MessageCircleQuestion,NotebookPen,Sparkles,Tags,Target as TargetIcon,Wand2,Link as LinkIcon} from 'lucide-react';
import {AIContentInput,requestAI,recordAILearningItem} from '../lib/ai';
import {notifyToast} from '../lib/toast';

type Props={input:AIContentInput;selectedText?:string;compact?:boolean;onCreateNote?:(text:string)=>void};
export const AIAssistantPanel:React.FC<Props>=({input,selectedText,onCreateNote})=>{
 const [open,setOpen]=useState(false); const [task,setTask]=useState<any>('summary'); const [busy,setBusy]=useState(false); const [data,setData]=useState<any>(null); const [question,setQuestion]=useState(''); const [mode,setMode]=useState('standard'); const [advancedSource,setAdvancedSource]=useState(''); const [showAdvancedSource,setShowAdvancedSource]=useState(false);
 const source={...input,content:selectedText?.trim()||input.content};
 const saveNote=(text:string)=>{if(onCreateNote){onCreateNote(text);return;}try{const k='offscrpt:ai:notes:v1';const old=JSON.parse(localStorage.getItem(k)||'[]');localStorage.setItem(k,JSON.stringify([...old,{id:Date.now().toString(),title:input.title,text:text.slice(0,5000),createdAt:new Date().toISOString(),contentType:input.contentType,contentId:input.contentId||''}].slice(-100)));notifyToast('AI note saved locally.','success')}catch(error){console.warn('AI note save skipped:',error);notifyToast('Could not save AI note.','error')}};
 const run=async(next=task,extra:any={})=>{setBusy(true);try{const requestSource=(next==='compare'||next==='synthesize')&&advancedSource.trim()?{...source,content:`SOURCE A\n${source.content}\n\nSOURCE B\n${advancedSource.trim()}`} : source; const result=await requestAI(next,requestSource,{mode,...extra});setData(result);setTask(next);setOpen(true); recordAILearningItem({topic:input.contentType,title:input.title,content:String((result as any)?.overview||(result as any)?.answer||(result as any)?.recap||JSON.stringify(result))});}catch(e:any){notifyToast(e?.message||'AI unavailable.','error')}finally{setBusy(false)}};
 const title=task.toUpperCase();
 return <section className="my-8 border-4 border-black bg-[var(--color-primary)] p-4 neo-shadow-lg">
   <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Bot className="w-5 h-5"/><div><div className="font-mono text-[9px] font-black uppercase">V79 AI READING & LEARNING</div><h3 className="font-display font-black text-2xl uppercase">AI READING ASSISTANT</h3></div></div><button onClick={()=>setOpen(v=>!v)} className="border-2 border-black bg-white px-3 py-2 font-mono text-[10px] font-black uppercase">{open?'CLOSE':'OPEN'} <ChevronDown className="inline w-4 h-4"/></button></div>
   <div className="mt-4 flex flex-wrap gap-2">
     {[['summary','SUMMARIZE',Sparkles],['explain','EXPLAIN',Lightbulb],['ask','ASK AI',MessageCircleQuestion],['concepts','KEY CONCEPTS',Brain],['analyze','INTELLIGENCE',Bot],['tags','TAGS',Tags],['prerequisites','PREREQUISITES',TargetIcon],['learning','LEARN THIS',GraduationCap],['quiz','CREATE QUESTIONS',FileQuestion],['flashcards','FLASHCARDS',NotebookPen],['quality','QUALITY CHECK',Check],['semantic','SEMANTIC',Brain],['creator','CREATOR AI',Wand2],['related','RELATED',LinkIcon]].map(([k,l,I]:any)=><button key={k} onClick={()=>k==='ask'?setOpen(true):void run(k as any)} className="border-2 border-black bg-white px-2 py-2 font-mono text-[9px] font-black uppercase inline-flex items-center gap-1"><I className="w-3 h-3"/>{l}</button>)}
     <button onClick={()=>{setTask('compare');setShowAdvancedSource(true);setOpen(true)}} className="border-2 border-black bg-white px-2 py-2 font-mono text-[9px] font-black uppercase">COMPARE</button>
     <button onClick={()=>{setTask('synthesize');setShowAdvancedSource(true);setOpen(true)}} className="border-2 border-black bg-white px-2 py-2 font-mono text-[9px] font-black uppercase">SYNTHESIZE</button>
     <select value={mode} onChange={e=>setMode(e.target.value)} className="border-2 border-black bg-white px-2 py-2 font-mono text-[9px] font-black uppercase"><option value="tldr">TL;DR</option><option value="quick">QUICK</option><option value="standard">STANDARD</option><option value="deep">DEEP</option><option value="expert">EXPERT</option><option value="beginner">BEGINNER MODE</option><option value="study">STUDY MODE</option><option value="revision">REVISION MODE</option><option value="deep-dive">DEEP DIVE MODE</option></select>
   </div>
   {(task==='compare'||task==='synthesize')&&<div className="mt-3"><button onClick={()=>setShowAdvancedSource(v=>!v)} className="border-2 border-black bg-white px-2 py-2 font-mono text-[9px] font-black">{showAdvancedSource?'HIDE':'ADD'} SECOND SOURCE</button>{showAdvancedSource&&<><textarea value={advancedSource} onChange={e=>setAdvancedSource(e.target.value)} placeholder="Paste the second article, answer, discussion or source here…" className="mt-2 w-full min-h-36 border-2 border-black bg-white p-3 text-sm"/><button onClick={()=>void run(task)} disabled={busy||!advancedSource.trim()} className="mt-2 border-2 border-black bg-black text-white px-3 py-2 font-mono text-[9px] font-black">RUN {task.toUpperCase()}</button></>}</div>}
   {task==='ask'&&<div className="mt-3 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void run('ask',{question})}} placeholder="Ask something about this content…" className="flex-1 border-2 border-black px-3 py-2 text-sm bg-white"/><button onClick={()=>question.trim()?void run('ask',{question}):notifyToast('Enter a question first.','error')} className="border-2 border-black bg-black text-white px-4 py-2 font-mono text-[9px] font-black">ASK</button></div>}
   {busy&&<div className="mt-4 bg-white border-2 border-black p-4 font-mono text-[10px] font-black uppercase"><Loader2 className="inline w-4 h-4 animate-spin mr-2"/>Gemini is processing grounded source context…</div>}
   {open&&data&&!busy&&<div className="mt-4 border-2 border-black bg-white p-4 space-y-4 max-h-[60vh] overflow-auto">
     <div className="flex justify-between gap-3"><div className="font-mono text-[9px] font-black uppercase">{title} · AI GENERATED · GROUNDED</div><div className="flex gap-1"><button onClick={()=>navigator.clipboard?.writeText(JSON.stringify(data,null,2))} className="border border-black p-1" title="Copy"><Copy className="w-3 h-3"/></button><button onClick={()=>saveNote(data.overview||data.answer||JSON.stringify(data))} className="border border-black p-1" title="Save note"><NotebookPen className="w-3 h-3"/></button></div></div>
     {data.overview&&<p className="text-sm leading-relaxed">{data.overview}</p>}{data.answer&&<div><div className="font-mono text-[9px] font-black mb-1">ANSWER</div><p className="text-sm leading-relaxed">{data.answer}</p></div>}
     {data.whyItMatters&&<Block title="WHY IT MATTERS" values={[data.whyItMatters]}/>} {data.conclusion&&<Block title="CONCLUSION" values={[data.conclusion]}/>} {data.uncertainty&&<div className="border-2 border-black bg-neutral-50 p-2 font-mono text-[9px] uppercase">{data.uncertainty}</div>}
     {data.keyPoints&&<Block title="KEY POINTS" values={data.keyPoints}/>} {data.arguments&&<Block title="MAIN ARGUMENTS" values={data.arguments}/>} {data.claims&&<Block title="CLAIMS" values={data.claims}/>} {data.terminology&&<Block title="TERMINOLOGY" values={data.terminology}/>} {data.prerequisites&&<Block title="PREREQUISITES" values={data.prerequisites}/>} {data.openQuestions&&<Block title="OPEN QUESTIONS" values={data.openQuestions}/>} {data.relatedConcepts&&<Block title="RELATED CONCEPTS" values={data.relatedConcepts}/>} {data.tags&&<Block title="AI SUGGESTED TAGS" values={data.tags.map((x:string)=>`#${x.replace(/^#/,'')}`)}/>} 
     {Array.isArray(data.concepts)&&<div><div className="font-mono text-[9px] font-black mb-2">CONCEPT MAP</div><div className="grid sm:grid-cols-2 gap-2">{data.concepts.slice(0,20).map((c:any,i:number)=><div key={i} className="border-2 border-black p-3"><b className="font-display uppercase">{c.name||c.title||`Concept ${i+1}`}</b><p className="text-xs mt-1">{c.definition||c.description||''}</p></div>)}</div></div>}
     {Array.isArray(data.questions)&&<div><div className="font-mono text-[9px] font-black mb-2">CHECK YOUR UNDERSTANDING</div>{data.questions.slice(0,10).map((q:any,i:number)=><div key={i} className="border-2 border-black p-3 mb-2"><b>{q.question||q.prompt}</b>{q.answer&&<div className="mt-2 text-xs text-neutral-700">Answer: {q.answer}</div>}</div>)}</div>}
     {Array.isArray(data.cards)&&<div><div className="font-mono text-[9px] font-black mb-2">FLASHCARDS</div>{data.cards.slice(0,12).map((c:any,i:number)=><details key={i} className="border-2 border-black p-3 mb-2"><summary className="font-display font-black uppercase cursor-pointer">{c.front||c.question||`Card ${i+1}`}</summary><p className="mt-2 text-sm">{c.back||c.answer||''}</p></details>)}</div>}
     {data.meta&&<div className="pt-2 border-t-2 border-black font-mono text-[8px] text-neutral-500 uppercase">MODEL {data.meta.model} · GENERATED {data.meta.generatedAt}</div>}
   </div>}
 </section>;
};
const Block:React.FC<{title:string;values:any[]}>=({title,values})=><div><div className="font-mono text-[9px] font-black mb-1">{title}</div><ul className="list-disc ml-5 text-sm space-y-1">{values.filter(Boolean).slice(0,12).map((v:any,i:number)=><li key={i}>{typeof v==='string'?v:JSON.stringify(v)}</li>)}</ul></div>;
