import { notifyToast } from '../lib/toast';
import React, { useMemo, useState } from 'react';
import { Article, CreatorPageConfig, Series } from '../types';
import { updateCommunityProfile } from '../lib/community';
import { Save, Layout, ArrowUp, ArrowDown, Plus, Trash2, Eye } from 'lucide-react';

interface Props { profile: any; articles: Article[]; series: Series[]; onSaved: (config: CreatorPageConfig)=>void; }
const cleanUrl=(value:string)=>{const v=value.trim();if(!v)return '';try{const u=new URL(v,window.location.origin);if(!['http:','https:','mailto:'].includes(u.protocol))return '';return u.href}catch{return ''}};

export const CreatorPageBuilder: React.FC<Props> = ({ profile, articles, series, onSaved }) => {
  const existing: CreatorPageConfig = profile.creatorPage || {};
  const [config,setConfig]=useState<CreatorPageConfig>({ layout:'grid', themeColor:profile.themeColor||'#D97706', showStats:true, showSocialLinks:true, showAbout:true, ...existing });
  const [saving,setSaving]=useState(false);
  const [articleQuery,setArticleQuery]=useState('');
  const [seriesQuery,setSeriesQuery]=useState('');
  const [linkLabel,setLinkLabel]=useState('');
  const [linkUrl,setLinkUrl]=useState('');
  const chosenArticles = config.featuredArticleSlugs || [];
  const chosenSeries = config.featuredSeriesIds || [];
  const filteredArticles=useMemo(()=>articles.filter(a=>!articleQuery||a.title.toLowerCase().includes(articleQuery.toLowerCase())).slice(0,12),[articles,articleQuery]);
  const filteredSeries=useMemo(()=>series.filter(s=>!seriesQuery||s.title.toLowerCase().includes(seriesQuery.toLowerCase())).slice(0,12),[series,seriesQuery]);
  const toggle=(key:'featuredArticleSlugs'|'featuredSeriesIds',id:string)=>setConfig(c=>({...c,[key]:((c[key]||[]).includes(id)?(c[key]||[]).filter(x=>x!==id):[...(c[key]||[]),id]).slice(0,8)}));
  const move=(key:'featuredArticleSlugs'|'featuredSeriesIds',idx:number,dir:-1|1)=>setConfig(c=>{const arr=[...(c[key]||[])];const t=idx+dir;if(t<0||t>=arr.length)return c;[arr[idx],arr[t]]=[arr[t],arr[idx]];return {...c,[key]:arr}});
  const addLink=()=>{const url=cleanUrl(linkUrl); if(!linkLabel.trim()||!url){notifyToast('Enter a valid link label and http(s)/mailto URL.','error');return;} const item={id:crypto.randomUUID(),label:linkLabel.trim().slice(0,50),url}; setConfig(c=>({...c,customLinks:[...(c.customLinks||[]),item].slice(0,8)}));setLinkLabel('');setLinkUrl('');};
  const save=async()=>{setSaving(true);try{await updateCommunityProfile(profile.uid,{creatorPage:config});onSaved(config);notifyToast('Creator page saved and synced.','success');}catch(e:any){notifyToast(e?.message||'Could not save creator page.','error');}finally{setSaving(false)}};
  return <div className="border-4 border-black bg-white p-5 space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="font-mono text-[10px] uppercase text-neutral-500">CREATOR PAGE BUILDER</div><h3 className="font-display font-black text-2xl uppercase">Build your public page</h3></div><button onClick={()=>window.open(`${window.location.origin}/#creator/${profile.username}`,'_blank','noopener,noreferrer')} className="border-2 border-black bg-[var(--color-secondary)] px-3 py-2 font-mono text-[9px] font-black uppercase inline-flex items-center gap-2"><Eye className="w-3 h-3"/> PREVIEW</button></div>
    <div className="grid md:grid-cols-2 gap-3"><label><span className="font-mono text-[9px] uppercase font-black">Hero title</span><input value={config.heroTitle||''} onChange={e=>setConfig(c=>({...c,heroTitle:e.target.value}))} placeholder="Ideas by @username" className="w-full mt-1 border-2 border-black p-3"/></label><label><span className="font-mono text-[9px] uppercase font-black">Tagline</span><input value={config.tagline||''} onChange={e=>setConfig(c=>({...c,tagline:e.target.value}))} placeholder="Developer · Builder" className="w-full mt-1 border-2 border-black p-3"/></label></div>
    <textarea value={config.heroText||''} onChange={e=>setConfig(c=>({...c,heroText:e.target.value}))} placeholder="Hero description" rows={4} className="w-full border-2 border-black p-3"/>
    <div className="grid md:grid-cols-2 gap-3"><label><span className="font-mono text-[9px] uppercase font-black">Hero cover image URL</span><input value={config.coverImageUrl||''} onChange={e=>setConfig(c=>({...c,coverImageUrl:e.target.value}))} placeholder="https://..." className="w-full mt-1 border-2 border-black p-3 font-mono text-xs"/></label><label><span className="font-mono text-[9px] uppercase font-black">About title</span><input value={config.aboutTitle||''} onChange={e=>setConfig(c=>({...c,aboutTitle:e.target.value}))} placeholder="About the creator" className="w-full mt-1 border-2 border-black p-3"/></label></div>
    <div className="grid sm:grid-cols-4 gap-2"><label className="border-2 border-black p-3 font-mono text-xs">THEME <input type="color" value={config.themeColor||'#D97706'} onChange={e=>setConfig(c=>({...c,themeColor:e.target.value}))} className="float-right"/></label>{(['grid','list','magazine'] as const).map(l=><button key={l} onClick={()=>setConfig(c=>({...c,layout:l}))} className={`border-2 border-black p-3 font-mono text-xs uppercase ${config.layout===l?'bg-[var(--color-primary)] font-black':''}`}><Layout className="inline w-4 h-4 mr-1"/>{l}</button>)} </div>
    <div className="flex flex-wrap gap-3 font-mono text-[10px] uppercase"><label className="inline-flex items-center gap-2"><input type="checkbox" checked={config.showStats??true} onChange={e=>setConfig(c=>({...c,showStats:e.target.checked}))}/> Show stats</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={config.showAbout??true} onChange={e=>setConfig(c=>({...c,showAbout:e.target.checked}))}/> Show about</label><label className="inline-flex items-center gap-2"><input type="checkbox" checked={config.showSocialLinks??true} onChange={e=>setConfig(c=>({...c,showSocialLinks:e.target.checked}))}/> Show social links</label></div>
    <div className="border-2 border-black p-4"><h4 className="font-display font-black uppercase">Custom links</h4><div className="grid md:grid-cols-[1fr_2fr_auto] gap-2 mt-2"><input value={linkLabel} onChange={e=>setLinkLabel(e.target.value)} placeholder="Label" className="border-2 border-black p-2 font-mono text-xs"/><input value={linkUrl} onChange={e=>setLinkUrl(e.target.value)} placeholder="https://..." className="border-2 border-black p-2 font-mono text-xs"/><button onClick={addLink} className="border-2 border-black bg-[var(--color-primary)] px-3 font-mono text-[10px] font-black"><Plus className="inline w-3 h-3"/> ADD</button></div>{(config.customLinks||[]).length>0&&<div className="mt-3 space-y-2">{(config.customLinks||[]).map((l,i)=><div key={l.id} className="flex items-center gap-2 border-2 border-black p-2"><span className="font-mono text-[10px] flex-1 truncate">{i+1}. {l.label} · {l.url}</span><button onClick={()=>setConfig(c=>({...c,customLinks:(c.customLinks||[]).filter(x=>x.id!==l.id)}))} className="border-2 border-black p-1"><Trash2 className="w-3 h-3"/></button></div>)}</div>}</div>
    <div className="grid lg:grid-cols-2 gap-5"><div className="border-2 border-black p-4"><h4 className="font-display font-black uppercase">Featured articles</h4><input value={articleQuery} onChange={e=>setArticleQuery(e.target.value)} placeholder="Filter articles" className="w-full border-2 border-black p-2 mt-2 font-mono text-xs"/><div className="space-y-2 mt-3">{filteredArticles.map(a=><button key={a.slug} onClick={()=>toggle('featuredArticleSlugs',a.slug)} className={`w-full text-left border-2 border-black p-2 text-sm ${chosenArticles.includes(a.slug)?'bg-[var(--color-primary)]':''}`}>{chosenArticles.includes(a.slug)?'✓ ':''}{a.title}</button>)}</div><div className="mt-3 space-y-1">{chosenArticles.map((id,i)=><div key={id} className="flex gap-1"><div className="flex-1 border-2 border-black p-2 font-mono text-[10px]">{i+1}. {articles.find(a=>a.slug===id)?.title||id}</div><button onClick={()=>move('featuredArticleSlugs',i,-1)} className="border-2 border-black p-2"><ArrowUp className="w-3 h-3"/></button><button onClick={()=>move('featuredArticleSlugs',i,1)} className="border-2 border-black p-2"><ArrowDown className="w-3 h-3"/></button></div>)}</div></div><div className="border-2 border-black p-4"><h4 className="font-display font-black uppercase">Featured series</h4><input value={seriesQuery} onChange={e=>setSeriesQuery(e.target.value)} placeholder="Filter series" className="w-full border-2 border-black p-2 mt-2 font-mono text-xs"/><div className="space-y-2 mt-3">{filteredSeries.map(s=><button key={s.id} onClick={()=>toggle('featuredSeriesIds',s.id)} className={`w-full text-left border-2 border-black p-2 text-sm ${chosenSeries.includes(s.id)?'bg-[var(--color-secondary)]':''}`}>{chosenSeries.includes(s.id)?'✓ ':''}{s.title}</button>)}</div><div className="mt-3 space-y-1">{chosenSeries.map((id,i)=><div key={id} className="flex gap-1"><div className="flex-1 border-2 border-black p-2 font-mono text-[10px]">{i+1}. {series.find(s=>s.id===id)?.title||id}</div><button onClick={()=>move('featuredSeriesIds',i,-1)} className="border-2 border-black p-2"><ArrowUp className="w-3 h-3"/></button><button onClick={()=>move('featuredSeriesIds',i,1)} className="border-2 border-black p-2"><ArrowDown className="w-3 h-3"/></button></div>)}</div></div></div>
    <button onClick={save} disabled={saving} className="border-2 border-black bg-black text-white px-5 py-3 font-mono text-xs font-black uppercase">{saving?'SAVING…':'SAVE CREATOR PAGE'}</button>
  </div>
};
