import React, { useMemo } from 'react';
import { BarChart3, BookOpen, MessageCircle, Sparkles, Users, Heart } from 'lucide-react';
import type { Article, CommunityUser, PageView } from '../types';
import { subscribeArticleEngagementStats } from '../lib/reading';
import { collection, getCountFromServer, query, where, getDocs } from 'firebase/firestore';
import { db } from '../lib/firebase';

interface Props { articles:Article[]; userProfile:CommunityUser|null; onNavigate:(page:PageView,param?:string)=>void; }
const published=(a:Article)=>a.isPublished!==false&&a.mainPublicationStatus!=='unpublished';
export const CreatorDashboardView:React.FC<Props>=({articles,userProfile,onNavigate})=>{
 const mine=useMemo(()=>articles.filter(a=>published(a)&&((a.author?.uid&&a.author.uid===userProfile?.uid)||(a.author?.username&&a.author.username===userProfile?.username))),[articles,userProfile?.uid,userProfile?.username]);
 const [stats,setStats]=React.useState<Record<string,{views:number;reactions:number;comments:number}>>({});
 React.useEffect(()=>{let dead=false;Promise.all(mine.map(async a=>{let reactions=0,comments=0;try{const snap=await getDocs(collection(db,'articles',a.slug,'reactions'));reactions=snap.size}catch{}try{comments=(await getCountFromServer(collection(db,'articles',a.slug,'comments'))).data().count}catch{}return [a.slug,{views:Number(a.viewsCount||0),reactions,comments}] as const})).then(rows=>!dead&&setStats(Object.fromEntries(rows)));return()=>{dead=true}},[mine.map(a=>a.slug).join('|')]);
 const totals=useMemo(()=>{const rows=mine.map(a=>stats[a.slug]||{views:Number(a.viewsCount||0),reactions:0,comments:0});return {views:rows.reduce((n,x)=>n+x.views,0),reactions:rows.reduce((n,x)=>n+x.reactions,0),comments:rows.reduce((n,x)=>n+x.comments,0)}},[mine,stats]);
 const top=[...mine].sort((a,b)=>(stats[b.slug]?.views||Number(b.viewsCount||0))-(stats[a.slug]?.views||Number(a.viewsCount||0)))[0];
 if(!userProfile)return <div className="max-w-3xl mx-auto py-24 text-center font-mono text-sm">SIGN IN TO OPEN CREATOR STUDIO.</div>;
 return <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-14 space-y-6"><header className="border-4 border-black bg-black text-white p-6 sm:p-9 neo-shadow-lg"><div className="font-mono text-[10px] uppercase text-[var(--color-primary)] font-black flex items-center gap-2"><BarChart3 className="w-4 h-4"/> Creator Studio</div><h1 className="font-display font-black text-4xl sm:text-6xl uppercase mt-2">Creator Dashboard</h1><p className="mt-3 max-w-2xl text-neutral-300">Live metrics calculated from your published OFFSCRPT content.</p></header><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="ARTICLES" value={String(mine.length)} icon={<BookOpen/>}/><Metric label="READERS / VIEWS" value={totals.views.toLocaleString()} icon={<Users/>}/><Metric label="REACTIONS" value={totals.reactions.toLocaleString()} icon={<Heart/>}/><Metric label="COMMENTS" value={totals.comments.toLocaleString()} icon={<MessageCircle/>}/></div>{top?<section className="border-4 border-black bg-[var(--color-primary)] p-6 neo-shadow"><div className="font-mono text-[10px] uppercase font-black">TOP ARTICLE</div><h2 className="font-display font-black text-3xl uppercase mt-1">{top.title}</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-5">{[ ['VIEWS',String(stats[top.slug]?.views??Number(top.viewsCount||0))], ['REACTIONS',String(stats[top.slug]?.reactions??0)], ['COMMENTS',String(stats[top.slug]?.comments??0)], ['READ TIME',`${top.readingTimeMinutes||0} MIN`] ].map(([l,v])=><div key={l} className="border-2 border-black bg-white p-3"><div className="font-mono text-[9px]">{l}</div><div className="font-display font-black text-2xl">{v}</div></div>)}</div><button onClick={()=>onNavigate('article',top.slug)} className="mt-5 border-2 border-black bg-black text-white px-4 py-2 font-mono text-[10px] font-black uppercase">OPEN ARTICLE →</button></section>:<div className="border-4 border-dashed border-black p-10 text-center font-mono text-xs uppercase">PUBLISH YOUR FIRST ARTICLE TO POPULATE CREATOR ANALYTICS.</div>}<section><div className="flex items-end justify-between mb-3"><h2 className="font-display font-black text-3xl uppercase">Your Articles</h2><span className="font-mono text-[9px]">LIVE FIRESTORE METRICS</span></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{mine.map(a=><button key={a.slug} onClick={()=>onNavigate('article',a.slug)} className="text-left border-4 border-black bg-white p-4 hover:bg-[var(--color-secondary)]"><div className="font-mono text-[9px] uppercase">{a.category} · {a.readingTimeMinutes||0} MIN</div><h3 className="font-display font-black text-xl uppercase mt-1">{a.title}</h3><div className="mt-4 flex gap-2 font-mono text-[9px]"><span>{stats[a.slug]?.views??Number(a.viewsCount||0)} VIEWS</span><span>{stats[a.slug]?.reactions??0} REACTIONS</span></div></button>)}</div></section></div>;
};
const Metric=({label,value,icon}:{label:string;value:string;icon:React.ReactNode})=><div className="border-2 border-black bg-white p-4"><div className="flex items-center gap-2 font-mono text-[9px] font-black uppercase">{icon}{label}</div><div className="font-display font-black text-3xl mt-2">{value}</div></div>;
