import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,BookOpen,MessageCircle,Users,Heart,Clock,Share2,Bookmark,Eye,RotateCcw} from 'lucide-react';
import type {Article,CommunityUser,PageView,Series} from '../types';
import {collection,getCountFromServer} from 'firebase/firestore';
import {db} from '../lib/firebase';
import {getArticleAnalyticsAggregate,ArticleAnalyticsAggregate} from '../lib/analytics';
import {getSeriesList} from '../lib/series';
import {getSeriesArticles,createArticleRevision,getArticleRevisions,restoreArticleRevision} from '../lib/cms';
import {notifyToast} from '../lib/toast';
interface Props{articles:Article[];userProfile:CommunityUser|null;onNavigate:(page:PageView,param?:string)=>void}
const published=(a:Article)=>a.isPublished!==false&&a.mainPublicationStatus!=='unpublished'; const timeLabel=(ms:number)=>{const s=Math.round(ms/1000);return s<60?`${s}s`:`${Math.floor(s/60)}m ${s%60}s`};
export const CreatorDashboardView:React.FC<Props>=({articles,userProfile,onNavigate})=>{
 const mine=useMemo(()=>articles.filter(a=>published(a)&&((a.author?.uid&&a.author.uid===userProfile?.uid)||(a.author?.username&&a.author.username===userProfile?.username))),[articles,userProfile?.uid,userProfile?.username]);
 const [range,setRange]=useState<number|'all'>(30); const [stats,setStats]=useState<Record<string,ArticleAnalyticsAggregate>>({}); const [series,setSeries]=useState<Series[]>([]); const [selected,setSelected]=useState<string|null>(null); const [seriesData,setSeriesData]=useState<any[]>([]); const [revisions,setRevisions]=useState<any[]>([]); const [busy,setBusy]=useState(true);
 useEffect(()=>{let dead=false;setBusy(true);Promise.all(mine.map(async a=>{const x=await getArticleAnalyticsAggregate(a.slug,Number(a.viewsCount||0),range);let comments=0;try{comments=(await getCountFromServer(collection(db,'articles',a.slug,'comments'))).data().count}catch{}return [a.slug,{...x,comments}] as const})).then(rows=>{if(!dead)setStats(Object.fromEntries(rows))}).finally(()=>{if(!dead)setBusy(false)});return()=>{dead=true}},[mine.map(a=>a.slug).join('|'),range]);
 useEffect(()=>{getSeriesList(100).then(s=>setSeries(s.filter(x=>x.ownerId===userProfile?.uid||x.ownerUsername===userProfile?.username))).catch(()=>setSeries([]))},[userProfile?.uid,userProfile?.username]);
 const totals=useMemo(()=>{const r=mine.map(a=>stats[a.slug]);return{views:r.reduce((n,x)=>n+(x?.views||0),0),unique:r.reduce((n,x)=>n+(x?.uniqueReaders||0),0),returning:r.reduce((n,x)=>n+(x?.returnReaders||0),0),reactions:r.reduce((n,x)=>n+(x?.reactions||0),0),comments:r.reduce((n,x)=>n+(x?.comments||0),0),shares:r.reduce((n,x)=>n+(x?.shares||0),0),bookmarks:r.reduce((n,x)=>n+(x?.bookmarks||0),0)}} , [mine,stats]);
 const top=useMemo(()=>[...mine].sort((a,b)=>(stats[b.slug]?.views||0)-(stats[a.slug]?.views||0))[0],[mine,stats]);
 const openSeries=async(id:string)=>{setSelected(id);try{const sa=await getSeriesArticles(id);const rows=await Promise.all(sa.map(async a=>({article:a,stats:await getArticleAnalyticsAggregate(a.slug,Number(a.viewsCount||0),range)})));setSeriesData(rows)}catch{setSeriesData([])}};
 const openRevisions=async(a:Article)=>{try{setRevisions(await getArticleRevisions(a.slug));setSelected(`rev:${a.slug}`)}catch{setRevisions([])}};
 if(!userProfile)return <div className="max-w-3xl mx-auto py-24 text-center font-mono text-sm">SIGN IN TO OPEN CREATOR STUDIO.</div>;
 const Funnel=({x}:{x:ArticleAnalyticsAggregate})=><div className="space-y-2 mt-4">{[['OPENED',x.funnel.opened],['25%',x.funnel.p25],['50%',x.funnel.p50],['75%',x.funnel.p75],['COMPLETED',x.funnel.completed]].map(([l,v]:any)=><div key={l}><div className="flex justify-between font-mono text-[9px] font-black"><span>{l}</span><span>{Number(v).toLocaleString()}</span></div><div className="h-3 border-2 border-black bg-neutral-100"><div className="h-full bg-[var(--color-primary)]" style={{width:`${Math.max(1,Math.min(100,Number(v)/(x.funnel.opened||1)*100))}%`}}/></div></div>)}</div>;
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 py-10 space-y-7">
  <header className="border-4 border-black bg-black text-white p-6 sm:p-9 neo-shadow-lg"><div className="font-mono text-[10px] text-[var(--color-primary)] font-black flex items-center gap-2"><BarChart3 className="w-4 h-4"/> CREATOR ANALYTICS</div><h1 className="font-display font-black text-4xl sm:text-6xl uppercase mt-2">Creator Dashboard</h1><p className="text-neutral-300 mt-3">Aggregate reader analytics. Individual reader identities are never exposed here.</p><div className="flex flex-wrap gap-2 mt-5">{([7,30,90,'all'] as const).map(r=><button key={String(r)} onClick={()=>setRange(r)} className={`border-2 border-white px-3 py-2 font-mono text-[10px] font-black ${range===r?'bg-[var(--color-primary)] text-black':'bg-black text-white'}`}>{r==='all'?'ALL TIME':`${r}D`}</button>)}</div></header>
  {busy?<div className="border-2 border-black p-8 font-mono text-xs">LOADING CLOUD ANALYTICS…</div>:<>
  <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-3">{[['READERS',totals.views,Users],['UNIQUE',totals.unique,Eye],['RETURNING',totals.returning,Users],['AVG TIME',top?timeLabel(stats[top.slug]?.averageReadingTimeMs||0):'0s',Clock],['SHARES',totals.shares,Share2],['BOOKMARKS',totals.bookmarks,Bookmark],['REACTIONS',totals.reactions,Heart]].map(([l,v,I]:any)=><div key={l} className="border-2 border-black bg-white p-3"><div className="font-mono text-[8px] font-black flex gap-1 items-center"><I className="w-3 h-3"/>{l}</div><div className="font-display font-black text-2xl mt-2">{typeof v==='number'?v.toLocaleString():v}</div></div>)}</div>
  {top&&<section className="grid lg:grid-cols-2 gap-4"><div className="border-4 border-black bg-[var(--color-primary)] p-5 neo-shadow"><div className="font-mono text-[9px] font-black">TOP ARTICLE · {top.title}</div><h2 className="font-display font-black text-3xl uppercase mt-2">{top.title}</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-5">{[['COMPLETION',`${stats[top.slug]?.completionRate||0}%`],['SCROLL',`${stats[top.slug]?.scrollDepth||0}%`],['COMMENTS',stats[top.slug]?.comments||0],['AVG',timeLabel(stats[top.slug]?.averageReadingTimeMs||0)]].map(([l,v])=><div key={l} className="border-2 border-black bg-white p-3"><div className="font-mono text-[8px]">{l}</div><div className="font-display font-black text-xl">{v}</div></div>)}</div></div><div className="border-4 border-black bg-white p-5"><div className="font-mono text-[9px] font-black">READING FUNNEL · {range==='all'?'ALL TIME':`${range} DAYS`}</div><Funnel x={stats[top.slug]}/></div></section>}
  <section><div className="flex justify-between items-end mb-3"><h2 className="font-display font-black text-3xl uppercase">Article Comparison</h2><span className="font-mono text-[9px]">{mine.length} PUBLISHED ARTICLES</span></div><div className="overflow-x-auto border-4 border-black bg-white"><table className="w-full text-left"><thead><tr className="bg-black text-white font-mono text-[9px]"><th className="p-3">ARTICLE</th><th className="p-3">READERS</th><th className="p-3">UNIQUE</th><th className="p-3">RETURNING</th><th className="p-3">AVG TIME</th><th className="p-3">COMPLETE</th><th className="p-3">SCROLL</th><th className="p-3">ENGAGEMENT</th></tr></thead><tbody>{mine.map(a=>{const x=stats[a.slug];return <tr key={a.slug} className="border-t-2 border-black"><td className="p-3 font-display font-black text-sm uppercase min-w-64">{a.title}</td><td className="p-3 font-mono text-xs">{x?.views||0}</td><td className="p-3 font-mono text-xs">{x?.uniqueReaders||0}</td><td className="p-3 font-mono text-xs">{x?.returnReaders||0}</td><td className="p-3 font-mono text-xs">{timeLabel(x?.averageReadingTimeMs||0)}</td><td className="p-3 font-mono text-xs">{x?.completionRate||0}%</td><td className="p-3 font-mono text-xs">{x?.scrollDepth||0}%</td><td className="p-3 font-mono text-xs">{(x?.shares||0)+(x?.bookmarks||0)+(x?.reactions||0)+(x?.comments||0)}</td></tr>})}</tbody></table></div></section>
  <section><h2 className="font-display font-black text-3xl uppercase mb-3">Series Analytics</h2><div className="grid md:grid-cols-2 gap-3">{series.map(s=><button key={s.id} onClick={()=>void openSeries(s.id)} className="border-4 border-black bg-white p-5 text-left hover:bg-[var(--color-secondary)]"><div className="font-mono text-[9px]">{s.articleCount||0} PARTS</div><div className="font-display font-black text-2xl uppercase">{s.title}</div><div className="font-mono text-[9px] mt-3">OPEN PART-BY-PART ANALYTICS →</div></button>)}</div></section>
  <section><h2 className="font-display font-black text-3xl uppercase mb-3">Revision History</h2><div className="grid md:grid-cols-2 gap-3">{mine.map(a=><div key={a.slug} className="border-2 border-black bg-white p-4 flex items-center justify-between gap-3"><div className="font-display font-black text-sm uppercase">{a.title}</div><div className="flex gap-2"><button onClick={()=>void openRevisions(a)} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black"><RotateCcw className="inline w-3 h-3"/> HISTORY</button><button onClick={async()=>{try{await createArticleRevision(a);notifyToast('Cloud revision snapshot created.','success')}catch(e:any){notifyToast(e?.message||'Snapshot failed.','error')}}} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black">SNAPSHOT</button></div></div>)}</div></section>
  {selected?.startsWith('rev:')&&<section className="border-4 border-black bg-white p-5"><div className="flex justify-between"><h2 className="font-display font-black text-2xl uppercase">Cloud Revisions</h2><button onClick={()=>setSelected(null)}>✕</button></div><div className="space-y-2 mt-4">{revisions.map(r=><div key={r.id} className="border-2 border-black p-3 flex justify-between gap-2"><div className="font-mono text-[9px]">{r.action||'revision'} · {r.createdAt?.toDate?.()?.toLocaleString?.()||'timestamp'}</div><button onClick={async()=>{try{await restoreArticleRevision(r.id);notifyToast('Revision restored.','success')}catch(e:any){notifyToast(e?.message||'Restore failed.','error')}}} className="border-2 border-black px-2 py-1 font-mono text-[9px] font-black">RESTORE</button></div>)}{!revisions.length&&<div className="font-mono text-xs">NO REVISIONS.</div>}</div></section>}
  {selected&&!selected.startsWith('rev:')&&<section className="border-4 border-black bg-white p-5"><div className="flex justify-between"><h2 className="font-display font-black text-2xl uppercase">SERIES PARTS</h2><button onClick={()=>setSelected(null)}>✕</button></div><div className="space-y-2 mt-4">{seriesData.map((r:any,i:number)=><div key={r.article.slug} className="border-2 border-black p-3"><div className="flex justify-between font-mono text-[9px] font-black"><span>PART {String(i+1).padStart(2,'0')} · {r.article.title}</span><span>{r.stats.views} READERS</span></div><Funnel x={r.stats}/></div>)}</div></section>}
  </>}
 </div>;
};
