import React, { useEffect, useState } from 'react';
import { Article, CreatorPageConfig, Series, CommunityUser } from '../types';
import { getProfileByUsername } from '../lib/community';
import { getSeriesList } from '../lib/series';
import { ArrowRight, BookOpen, Layers, UserPlus } from 'lucide-react';
import { VerifiedBadge } from './VerifiedBadge';

interface Props { username: string; articles: Article[]; onNavigate:(page:any,param?:string)=>void; }
export const CreatorView:React.FC<Props>=({username,articles,onNavigate})=>{
 const [profile,setProfile]=useState<CommunityUser|null>(null); const [series,setSeries]=useState<Series[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;Promise.all([getProfileByUsername(username),getSeriesList()]).then(([p,s])=>{if(!active)return;setProfile(p as any);setSeries(s as any)}).finally(()=>active&&setLoading(false));return()=>{active=false}},[username]);
 if(loading)return <div className="max-w-6xl mx-auto px-4 py-20 text-center font-mono text-xs">LOADING CREATOR…</div>;
 if(!profile)return <div className="max-w-xl mx-auto px-4 py-20 text-center"><div className="border-4 border-black p-10 font-mono text-xs">CREATOR NOT FOUND</div></div>;
 const cfg=(profile as any).creatorPage as CreatorPageConfig||{}; const theme=cfg.themeColor||profile.themeColor||'#FFD600';
 const authorArticles=articles.filter(a=>a.author?.uid===profile.uid||a.author?.username===profile.username); const featuredArticles=(cfg.featuredArticleSlugs||[]).map(id=>authorArticles.find(a=>a.slug===id)).filter(Boolean) as Article[];
 const featuredSeries=(cfg.featuredSeriesIds||[]).map(id=>series.find(s=>s.id===id)).filter(Boolean) as Series[];
 const shownArticles=featuredArticles.length?featuredArticles:authorArticles.slice(0,6);
 const ownSeries=series.filter(s=>s.ownerId===profile.uid||s.ownerUsername===profile.username); const shownSeries=featuredSeries.length?featuredSeries:ownSeries.slice(0,4);
 return <div className="min-h-screen" style={{'--creator-theme':theme} as any}>
  <div className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-7">
   <section className="border-4 border-black p-6 sm:p-10 neo-shadow-lg" style={{background:theme}}><div className="flex flex-wrap items-start justify-between gap-6"><div className="flex gap-4 items-center">{profile.photoURL?<img src={profile.photoURL} className="w-20 h-20 sm:w-24 sm:h-24 object-cover border-4 border-black"/>:<div className="w-20 h-20 border-4 border-black bg-white flex items-center justify-center font-display font-black text-3xl">{profile.displayName.charAt(0)}</div>}<div><div className="font-mono text-[10px] uppercase">CREATOR PAGE</div><h1 className="font-display font-black text-4xl sm:text-6xl uppercase">{profile.displayName}<VerifiedBadge verified={profile.isVerified} color={profile.verificationColor} className="inline w-6 h-6 ml-2"/></h1><div className="font-mono text-xs">@{profile.username}</div></div></div><div className="font-mono text-xs uppercase">{profile.followersCount||0} FOLLOWERS · {authorArticles.length} ARTICLES</div></div><p className="font-mono text-sm mt-6 max-w-3xl">{cfg.tagline||profile.role}</p><h2 className="font-display font-black text-3xl sm:text-5xl uppercase mt-2">{cfg.heroTitle||`Ideas by @${profile.username}`}</h2><p className="max-w-2xl mt-3 text-sm whitespace-pre-wrap">{cfg.heroText||profile.bio}</p></section>
   {shownSeries.length>0&&<section><div className="flex items-end justify-between mb-3"><div><div className="font-mono text-[10px] uppercase">SELECTED PATHS</div><h2 className="font-display font-black text-2xl uppercase">Series</h2></div><button onClick={()=>onNavigate('series')} className="font-mono text-[10px] underline">ALL SERIES →</button></div><div className="grid md:grid-cols-2 gap-4">{shownSeries.map(s=><button key={s.id} onClick={()=>onNavigate('series',s.id)} className="text-left border-4 border-black bg-white p-4 hover:bg-[var(--color-secondary)]"><div className="font-mono text-[10px]"><Layers className="inline w-3 h-3"/> {s.articleCount} PARTS</div><h3 className="font-display font-black text-xl uppercase mt-1">{s.title}</h3><p className="text-sm mt-1">{s.description}</p></button>)}</div></section>}
   <section><div className="mb-3"><div className="font-mono text-[10px] uppercase">SELECTED DISPATCHES</div><h2 className="font-display font-black text-2xl uppercase">Articles</h2></div><div className={`grid gap-4 ${cfg.layout==='list'?'grid-cols-1':cfg.layout==='magazine'?'md:grid-cols-2':'md:grid-cols-2 lg:grid-cols-3'}`}>{shownArticles.map(a=><button key={a.slug} onClick={()=>onNavigate('article',a.slug)} className="text-left border-4 border-black bg-white p-4 hover:bg-[var(--color-primary)]"><div className="font-mono text-[10px]">{a.category} · {a.readingTimeMinutes||0} MIN</div><h3 className="font-display font-black text-xl uppercase mt-1">{a.title}</h3><p className="text-sm mt-2 line-clamp-3">{a.excerpt}</p><div className="mt-4 font-mono text-[10px]">READ <ArrowRight className="inline w-3 h-3"/></div></button>)}</div></section>
   {(cfg.showStats??true)&&<section className="grid sm:grid-cols-3 gap-3"><div className="border-4 border-black p-4 bg-black text-white"><BookOpen className="w-5 h-5"/><b className="block font-display text-3xl">{authorArticles.length}</b><span className="font-mono text-[10px]">ARTICLES</span></div><div className="border-4 border-black p-4" style={{background:theme}}><Layers className="w-5 h-5"/><b className="block font-display text-3xl">{ownSeries.length}</b><span className="font-mono text-[10px]">SERIES</span></div><div className="border-4 border-black p-4 bg-white"><UserPlus className="w-5 h-5"/><b className="block font-display text-3xl">{profile.followersCount||0}</b><span className="font-mono text-[10px]">FOLLOWERS</span></div></section>}
  </div></div>;
};
