import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Clock3,Sparkles} from 'lucide-react';
import type {Article,PageView} from '../types';
import {buildRecommendationSections,RecommendationSection,RecommendationSignals,subscribeRecommendationSignals,saveColdStartTopics} from '../lib/recommendations';
import {getArticleHistory} from '../lib/reading';
interface Props{articles:Article[];series:import('../types').Series[];userAuth:any;onNavigate:(page:PageView,param?:string)=>void}
const Mini:React.FC<{a:Article;onOpen:()=>void}>=({a,onOpen})=><button onClick={onOpen} className="text-left border-4 border-black bg-white overflow-hidden hover:bg-[var(--color-primary)] transition-colors group">{a.coverImage?<div className="aspect-[16/9] border-b-4 border-black overflow-hidden bg-neutral-100"><img src={a.coverImage} alt={a.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"/></div>:<div className="aspect-[16/9] border-b-4 border-black bg-neutral-100 flex items-center justify-center font-mono text-[9px] uppercase">NO COVER</div>}<div className="p-4"><div className="font-mono text-[9px] uppercase text-neutral-500">{a.category} · {a.readingTimeMinutes||0} MIN</div><h3 className="font-display font-black text-xl uppercase mt-1 line-clamp-2">{a.title}</h3><p className="text-sm mt-2 line-clamp-2">{a.excerpt}</p></div></button>;
const TOPICS=['AI','WEB','DATABASES','SYSTEMS','DEVTOOLS','SECURITY','STARTUPS','LOCAL AI'];
const emptySignals:RecommendationSignals={history:[],saves:[],following:[],followedTopics:[],followedSeries:[],readingProgress:[],searches:[],reactions:[]};
export const PersonalizedHomeSections:React.FC<Props>=({articles,userAuth,onNavigate})=>{
 const [signals,setSignals]=useState<RecommendationSignals>(emptySignals);
 const [sections,setSections]=useState<RecommendationSection[]>([]);
 const [continueArticle,setContinueArticle]=useState<Article|null>(null);
 const [topicDraft,setTopicDraft]=useState<string[]>([]);
 const [topicSaving,setTopicSaving]=useState(false);
 useEffect(()=>{if(!userAuth?.uid){setSignals(emptySignals);setSections([]);setContinueArticle(null);return()=>{}};return subscribeRecommendationSignals(userAuth.uid,setSignals,error=>console.warn('Recommendation signal sync failed:',error));},[userAuth?.uid]);
 useEffect(()=>{if(!userAuth?.uid)return;setSections(buildRecommendationSections(articles,signals));const h=signals.history;const item=[...h].sort((a,b)=>{const da=a.viewedAt?.toDate?.()?.getTime?.()||new Date(a.viewedAt||0).getTime();const db=b.viewedAt?.toDate?.()?.getTime?.()||new Date(b.viewedAt||0).getTime();return db-da}).find(x=>Number(x.progress||0)>0&&Number(x.progress||0)<100);setContinueArticle(item?articles.find(a=>a.slug===item.slug)||null:null);},[articles,signals,userAuth?.uid]);
 const isColdStart=useMemo(()=>!signals.followedTopics.length&&!signals.history.length&&!signals.saves.length&&!signals.following.length&&articles.length>0,[signals,articles.length]);
 const toggleTopic=(topic:string)=>setTopicDraft(v=>v.includes(topic)?v.filter(x=>x!==topic):v.length>=5?v:[...v,topic]);
 const start=async()=>{if(topicDraft.length===0)return;setTopicSaving(true);try{await saveColdStartTopics(topicDraft);setTopicDraft([]);}catch(e){console.warn('Cold-start topic save failed:',e)}finally{setTopicSaving(false)}};
 if(!userAuth)return null;
 return <>{isColdStart&&<section className="max-w-7xl mx-auto px-4 sm:px-6 py-7 border-b-4 border-black"><div className="border-4 border-black bg-white p-6 neo-shadow"><div className="font-mono text-[9px] font-black uppercase">OFFSCRPT PERSONALIZATION / COLD START</div><h2 className="font-display font-black text-3xl uppercase mt-2">CHOOSE WHAT YOU CARE ABOUT</h2><p className="font-mono text-[10px] text-neutral-600 mt-2">These topics seed your real recommendation feed. You can change them later by following/unfollowing topics.</p><div className="flex flex-wrap gap-2 mt-4">{TOPICS.map(t=><button key={t} onClick={()=>toggleTopic(t)} className={`border-2 border-black px-3 py-2 font-mono text-[10px] font-black uppercase ${topicDraft.includes(t)?'bg-[var(--color-primary)]':'bg-white'}`}>{topicDraft.includes(t)?'✓ ':''}{t}</button>)}</div><button disabled={!topicDraft.length||topicSaving} onClick={()=>void start()} className="mt-4 border-2 border-black bg-black text-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">{topicSaving?'SAVING…':'START PERSONALIZATION →'}</button></div></section>}{continueArticle&&<section className="max-w-7xl mx-auto px-4 sm:px-6 py-7 border-b-4 border-black"><div className="border-4 border-black bg-black text-white p-5 neo-shadow-lg flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="font-mono text-[9px] text-[var(--color-primary)] font-black"><Clock3 className="inline w-3 h-3"/> CONTINUE READING</div><h2 className="font-display font-black text-3xl uppercase">{continueArticle.title}</h2></div><button onClick={()=>onNavigate('article',continueArticle.slug)} className="border-2 border-black bg-[var(--color-primary)] text-black px-5 py-3 font-mono text-[10px] font-black">RESUME →</button></div></section>}{sections.map(s=><section key={s.title} className="max-w-7xl mx-auto px-4 sm:px-6 py-9 border-b-4 border-black"><div className="mb-5"><div className="font-mono text-[9px] font-black uppercase"><Sparkles className="inline w-3 h-3"/> DATA-DRIVEN DISCOVERY</div><h2 className="font-display font-black text-3xl uppercase">{s.title}</h2>{s.reason&&<div className="font-mono text-[9px] mt-1">{s.reason}</div>}</div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{s.articles.slice(0,4).map(a=><Mini key={a.slug} a={a} onOpen={()=>onNavigate('article',a.slug)}/>)}</div></section>)}</>};
