import React,{useEffect,useMemo,useState} from 'react';
import { collection, getDocs, limit, orderBy, query } from 'firebase/firestore';
import { Clock3, Sparkles, SlidersHorizontal, X } from 'lucide-react';
import type {Article, CommunityPost, PageView, Series} from '../types';
import type {SocialCommunity, SocialQuestion, SocialTopic} from '../lib/social';
import { db } from '../lib/firebase';
import { optimizedGetDocs } from '../lib/firestoreOptimization';
import { PostMediaPreview } from './PostMediaPreview';
import { PollBlock } from './PollBlock';
import { getAllCommunityFeedPosts } from '../lib/social';
import { buildRecommendationSections, RecommendationSection, RecommendationSignals, subscribeRecommendationSignals, saveColdStartTopics, getFeedPreferences, updateFeedPreferences, applyFeedPreferences, buildChronologicalArticles, FeedPreferences } from '../lib/recommendations';

interface Props{articles:Article[];series:Series[];userAuth:any;onNavigate:(page:PageView,param?:string)=>void}

type FeedMode='algorithmic'|'chronological';
type FeedTab='for-you'|'following'|'latest'|'trending'|'discussions'|'communities';
type TrendingKind='articles'|'posts'|'questions'|'creators'|'communities'|'series'|'topics';
const TOPICS=['AI','WEB','DATABASES','SYSTEMS','DEVTOOLS','SECURITY','STARTUPS','LOCAL AI'];
const emptySignals:RecommendationSignals={history:[],saves:[],following:[],followedTopics:[],followedSeries:[],readingProgress:[],searches:[],reactions:[]};

const Mini:React.FC<{a:Article;onOpen:()=>void;reason?:string;onMenu?:(a:Article)=>void}>=({a,onOpen,reason,onMenu})=><article className="relative text-left border-4 border-black bg-white overflow-hidden hover:bg-[var(--color-primary)] transition-colors group">
  {onMenu&&<button type="button" aria-label="Recommendation options" title="Recommendation options" onClick={(e)=>{e.stopPropagation();onMenu(a)}} className="absolute right-2 top-2 z-10 w-8 h-8 border-2 border-black bg-white grid place-items-center hover:bg-[var(--color-primary)]"><SlidersHorizontal className="w-4 h-4"/></button>}
  <button type="button" onClick={onOpen} className="w-full text-left">
    {a.coverImage?<div className="aspect-[16/9] border-b-4 border-black overflow-hidden bg-neutral-100"><img src={a.coverImage} alt={a.coverImageAlt||a.title} loading="lazy" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"/></div>:<div className="aspect-[16/9] border-b-4 border-black bg-neutral-100 flex items-center justify-center font-mono text-[9px] uppercase">NO COVER</div>}
    <div className="p-4"><div className="font-mono text-[9px] uppercase text-neutral-500">{a.category} · {a.readingTimeMinutes||0} MIN</div><h3 className="font-display font-black text-xl uppercase mt-1 line-clamp-2">{a.title}</h3><p className="text-sm mt-2 line-clamp-2">{a.excerpt}</p>{reason&&<div className="mt-3 font-mono text-[9px] uppercase border-t-2 border-black pt-2">{reason}</div>}</div>
  </button>
</article>;

const PostMini:React.FC<{p:CommunityPost;onOpen:()=>void;userId?:string}>=({p,onOpen,userId})=><article className="text-left border-4 border-black bg-white overflow-hidden hover:bg-[var(--color-primary)] transition-colors group">
  <button type="button" onClick={onOpen} className="w-full text-left">{<PostMediaPreview post={p} />}{!p.coverImage && !(p.mediaUrls||[]).length && <div className="aspect-[16/9] border-b-4 border-black bg-neutral-100 flex items-center justify-center font-mono text-[9px] uppercase">DISCUSSION</div>}
  <div className="p-4"><div className="font-mono text-[9px] uppercase text-neutral-500">@{p.authorUsername} · {p.commentsCount||0} COMMENTS</div><h3 className="font-display font-black text-xl uppercase mt-1 line-clamp-2">{p.title||'Untitled discussion'}</h3><p className="text-sm mt-2 line-clamp-3">{p.excerpt||p.content}</p></div></button>
  {p.poll&&<PollBlock poll={p.poll} postId={p.id} communityId={(p as any).communityId} userId={userId} compact/>}
</article>;

const CommunityMini:React.FC<{c:SocialCommunity;onOpen:()=>void}>=({c,onOpen})=><button type="button" onClick={onOpen} className="text-left border-4 border-black bg-white overflow-hidden hover:bg-[var(--color-primary)] transition-colors group">
  {c.bannerUrl?<div className="aspect-[2.5/1] border-b-4 border-black overflow-hidden"><img src={c.bannerUrl} alt="" loading="lazy" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"/></div>:<div className="aspect-[2.5/1] border-b-4 border-black bg-neutral-100"/>}
  <div className="p-4"><div className="flex items-center gap-3"><div className="w-10 h-10 border-2 border-black overflow-hidden bg-neutral-200 grid place-items-center font-display font-black">{c.iconUrl?<img src={c.iconUrl} alt="" className="w-full h-full object-cover"/>:String(c.name||'C').charAt(0)}</div><div><div className="font-display font-black uppercase">{c.name}</div><div className="font-mono text-[9px]">{Number(c.membersCount||0).toLocaleString()} MEMBERS</div></div></div><p className="text-sm mt-3 line-clamp-2">{c.description}</p></div>
</button>;

export const PersonalizedHomeSections:React.FC<Props>=({articles,series,userAuth,onNavigate})=>{
 const [signals,setSignals]=useState<RecommendationSignals>(emptySignals);
 const [sections,setSections]=useState<RecommendationSection[]>([]);
 const [continueArticle,setContinueArticle]=useState<Article|null>(null);
 const [topicDraft,setTopicDraft]=useState<string[]>([]);
 const [topicSaving,setTopicSaving]=useState(false);
 const [feedMode,setFeedMode]=useState<FeedMode>('algorithmic');
 const [feedTab,setFeedTab]=useState<FeedTab>('for-you');
 const [prefs,setPrefs]=useState<FeedPreferences>({});
 const [optionArticle,setOptionArticle]=useState<Article|null>(null);
 const [extrasLoading,setExtrasLoading]=useState(false);
 const [discussions,setDiscussions]=useState<CommunityPost[]>([]);
 const [communities,setCommunities]=useState<SocialCommunity[]>([]);
 const [questions,setQuestions]=useState<SocialQuestion[]>([]);
 const [trendingKind,setTrendingKind]=useState<TrendingKind>('articles');
 const [extrasLoaded,setExtrasLoaded]=useState({discussions:false,communities:false,questions:false});

 useEffect(()=>{if(!userAuth?.uid){setSignals(emptySignals);setSections([]);setContinueArticle(null);setPrefs({});setFeedMode('algorithmic');setFeedTab('latest');return()=>{}};return subscribeRecommendationSignals(userAuth.uid,setSignals,error=>console.warn('Recommendation signal sync failed:',error));},[userAuth?.uid]);
 useEffect(()=>{if(!userAuth?.uid)return;let active=true;(async()=>{const p=await getFeedPreferences(userAuth.uid);if(!active)return;setPrefs(p);if(p.mode)setFeedMode(p.mode);})();return()=>{active=false}},[userAuth?.uid]);
 useEffect(()=>{if(!userAuth?.uid)return;const raw=buildRecommendationSections(articles,signals);const filtered=raw.map(s=>({...s,articles:applyFeedPreferences(s.articles,prefs)})).filter(s=>s.articles.length);setSections(filtered);const h=signals.history;const item=[...h].sort((a,b)=>{const da=a.viewedAt?.toDate?.()?.getTime?.()||new Date(a.viewedAt||0).getTime();const db=b.viewedAt?.toDate?.()?.getTime?.()||new Date(b.viewedAt||0).getTime();return db-da}).find(x=>Number(x.progress||0)>0&&Number(x.progress||0)<100);setContinueArticle(item?articles.find(a=>a.slug===item.slug)||null:null);},[articles,signals,prefs,userAuth?.uid]);
 useEffect(()=>{if(feedTab==='for-you'||feedTab==='following'||feedTab==='latest')return;let active=true;setExtrasLoading(true);(async()=>{try{
   if(feedTab==='discussions'&&!extrasLoaded.discussions){const [rootSnap, communityItems] = await Promise.all([optimizedGetDocs('home:discussions:v2',()=>getDocs(query(collection(db,'posts'),orderBy('createdAt','desc'),limit(40))),{ttlMs:120000,allowStaleOnQuota:true}), getAllCommunityFeedPosts()]); const rootItems=rootSnap.docs.map(d=>({id:d.id,...d.data()} as CommunityPost)).filter(p=>p.type==='discussion'); const combined=Array.from(new Map([...rootItems,...communityItems.filter((p:any)=>p.postType==='discussion').map((p:any)=>({id:p.id,...p,type:'discussion',authorName:p.authorName,authorAvatar:p.authorAvatar,authorUsername:p.authorUsername,upvotesCount:p.score||0,downvotesCount:0,commentsCount:p.commentsCount||0,isFeatured:!!p.isFeatured,createdAt:p.createdAt,updatedAt:p.updatedAt} as CommunityPost))].map(p=>[`${(p as any).communityId||'root'}:${p.id}`,p])).values()).sort((a:any,b:any)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()); if(active)setDiscussions(combined);if(active)setExtrasLoaded(v=>({...v,discussions:true}));}
   if((feedTab==='communities'||(feedTab==='trending'&&trendingKind==='communities'))&&!extrasLoaded.communities){const snap=await optimizedGetDocs('home:communities:v1',()=>getDocs(query(collection(db,'communities'),limit(30))),{ttlMs:180000,allowStaleOnQuota:true});if(active)setCommunities(snap.docs.map(d=>({id:d.id,...d.data()} as SocialCommunity)));if(active)setExtrasLoaded(v=>({...v,communities:true}));}
   if(feedTab==='trending'&&trendingKind==='posts'&&!discussions.length){const snap=await optimizedGetDocs('home:trending-posts:v1',()=>getDocs(query(collection(db,'posts'),limit(60))),{ttlMs:120000,allowStaleOnQuota:true});if(active)setDiscussions(snap.docs.map(d=>({id:d.id,...d.data()} as CommunityPost)));}
   if((feedTab==='for-you'||feedTab==='following')&&!extrasLoaded.questions){const snap=await optimizedGetDocs('home:for-you-questions:v1',()=>getDocs(query(collection(db,'questions'),orderBy('createdAt','desc'),limit(40))),{ttlMs:180000,allowStaleOnQuota:true});if(active)setQuestions(snap.docs.map(d=>({id:d.id,...d.data()} as SocialQuestion)).filter(q=>q.moderationState!=='REMOVED'));if(active)setExtrasLoaded(v=>({...v,questions:true}));}
   if(feedTab==='trending'&&trendingKind==='questions'&&!extrasLoaded.questions){const snap=await optimizedGetDocs('home:questions:v1',()=>getDocs(query(collection(db,'questions'),orderBy('createdAt','desc'),limit(40))),{ttlMs:120000,allowStaleOnQuota:true});if(active)setQuestions(snap.docs.map(d=>({id:d.id,...d.data()} as SocialQuestion)));if(active)setExtrasLoaded(v=>({...v,questions:true}));}
  }catch(e){console.warn('Home discovery extras failed:',e)}finally{if(active)setExtrasLoading(false)}})();return()=>{active=false}},[feedTab,trendingKind,extrasLoaded.discussions,extrasLoaded.communities,extrasLoaded.questions,discussions.length]);

 const isColdStart=useMemo(()=>!signals.followedTopics.length&&!signals.history.length&&!signals.saves.length&&!signals.following.length&&articles.length>0,[signals,articles.length]);
 const followingSet=useMemo(()=>new Set(signals.following.flatMap(x=>[String(x.uid||x.id||'').toLowerCase(),String(x.username||'').toLowerCase()]).filter(Boolean)),[signals.following]);
 const modeArticles=useMemo(()=>{const all=applyFeedPreferences(articles,prefs);if(feedTab==='latest')return buildChronologicalArticles(all,12,prefs);if(feedTab==='following'){const followed=all.filter(a=>followingSet.has(String(a.author?.uid||'').toLowerCase())||followingSet.has(String(a.author?.username||'').toLowerCase())).sort((a,b)=>new Date(b.publishedAt||0).getTime()-new Date(a.publishedAt||0).getTime()).slice(0,12);return userAuth?followed:buildChronologicalArticles(all,12,prefs);}if(feedTab==='trending')return [...all].sort((a,b)=>{const score=(x:Article)=>Number(x.viewsCount||0)+Object.values(x.reactionCounts||{}).reduce((n,v)=>n+Number(v||0),0)*8;return score(b)-score(a)}).slice(0,12);return userAuth?(sections.find(s=>s.title==='FOR YOU')?.articles||[]).slice(0,12):buildChronologicalArticles(all,12,prefs)},[articles,prefs,feedTab,followingSet,sections,userAuth]);
 const algorithmic=feedMode==='algorithmic';
 const displayedArticles=algorithmic?modeArticles:buildChronologicalArticles(modeArticles,12,prefs);
 const secondarySections=useMemo(()=>{
   const used=new Set<string>(displayedArticles.map(a=>a.slug));
   return sections.filter(s=>s.title!=='FOR YOU').map(s=>({...s,articles:s.articles.filter(a=>{if(used.has(a.slug))return false;used.add(a.slug);return true}).slice(0,4)})).filter(s=>s.articles.length);
 },[sections,displayedArticles]);

 const creatorRadar=useMemo(()=>{
   const map=new Map<string,{uid?:string;username?:string;name:string;avatar:string;articles:number;views:number;recent:number}>();
   applyFeedPreferences(articles,prefs).forEach(a=>{const key=String(a.author?.uid||a.author?.username||a.author?.name||a.slug);const prev=map.get(key)||{uid:a.author?.uid,username:a.author?.username,name:a.author?.name||'CREATOR',avatar:a.author?.avatar||'',articles:0,views:0,recent:0};prev.articles+=1;prev.views+=Number(a.viewsCount||0);if((Date.now()-new Date(a.publishedAt||0).getTime())<14*86400000)prev.recent+=1;map.set(key,prev)});
   return Array.from(map.values());
 },[articles,prefs]);
 const creatorRadarSorted=useMemo(()=>Array.from(creatorRadar).sort((a,b)=>(b.recent*20+b.views/100+b.articles*5)-(a.recent*20+a.views/100+a.articles*5)),[creatorRadar]);
 const trendingTopicRows=useMemo(()=>{const counts=new Map<string,number>();applyFeedPreferences(articles,prefs).forEach(a=>{[a.category,...(a.tags||[])].map(x=>String(x||'').trim()).filter(Boolean).forEach(t=>counts.set(t,(counts.get(t)||0)+Number(a.viewsCount||0)+1))});return Array.from(counts.entries()).sort((a,b)=>b[1]-a[1]).slice(0,8)},[articles,prefs]);
 const trendingItems=useMemo(()=>{
   if(trendingKind==='articles') return displayedArticles;
   if(trendingKind==='posts') return discussions.filter(p=>p.type!=='blog').sort((a,b)=>(Number(b.viewsCount||0)+Number(b.commentsCount||0)*6+Number(b.upvotesCount||0)*4)-(Number(a.viewsCount||0)+Number(a.commentsCount||0)*6+Number(a.upvotesCount||0)*4)).slice(0,8);
   if(trendingKind==='questions') return [...questions].sort((a,b)=>(Number(b.answersCount||0)*8+Number(b.upvotesCount||0)*4+Number(b.followersCount||0)*3)-(Number(a.answersCount||0)*8+Number(a.upvotesCount||0)*4+Number(a.followersCount||0)*3)).slice(0,8);
   if(trendingKind==='series') return [...series].filter(s=>s.status!=='archived'&&s.visibility!=='private').sort((a,b)=>(Number(b.viewsCount||0)+Number(b.articleCount||0)*5)-(Number(a.viewsCount||0)+Number(a.articleCount||0)*5)).slice(0,6);
   return [];
 },[trendingKind,displayedArticles,discussions,questions,series]);

 const toggleTopic=(topic:string)=>setTopicDraft(v=>v.includes(topic)?v.filter(x=>x!==topic):v.length>=5?v:[...v,topic]);
 const start=async()=>{if(topicDraft.length===0||!userAuth?.uid)return;setTopicSaving(true);try{await saveColdStartTopics(topicDraft);setTopicDraft([]);}catch(e){console.warn('Cold-start topic save failed:',e)}finally{setTopicSaving(false)}};
 const changeMode=async(mode:FeedMode)=>{setFeedMode(mode);if(userAuth?.uid){setPrefs(v=>({...v,mode}));try{await updateFeedPreferences(userAuth.uid,{mode})}catch(e){console.warn('Feed mode save failed:',e)}}};
 const mutatePref=async(type:'hidden'|'creator'|'topic'|'community',article:Article)=>{if(!userAuth?.uid)return;const next={...prefs};if(type==='hidden')next.hiddenContentIds=[...(prefs.hiddenContentIds||[]),article.slug];if(type==='creator')next.mutedCreators=[...(prefs.mutedCreators||[]),String(article.author?.username||article.author?.uid||'')];if(type==='topic')next.mutedTopics=[...(prefs.mutedTopics||[]),String(article.category||'')];if(type==='community'){const communityId=String((article as any).sourceCommunityId||(article as any).communityId||'');if(communityId)next.mutedCommunities=[...(prefs.mutedCommunities||[]),communityId];}setPrefs(next);setOptionArticle(null);try{await updateFeedPreferences(userAuth.uid,next)}catch(e){console.warn('Feed preference save failed:',e)}};
 return <>
  {isColdStart&&<section className="max-w-7xl mx-auto px-4 sm:px-6 py-7 border-b-4 border-black"><div className="border-4 border-black bg-white p-6 neo-shadow"><div className="font-mono text-[9px] font-black uppercase">OFFSCRPT PERSONALIZATION / COLD START</div><h2 className="font-display font-black text-3xl uppercase mt-2">CHOOSE WHAT YOU CARE ABOUT</h2><p className="font-mono text-[10px] text-neutral-600 mt-2">These topics seed your real recommendation feed. You can change them later by following/unfollowing topics.</p><div className="flex flex-wrap gap-2 mt-4">{TOPICS.map(t=><button key={t} type="button" onClick={()=>toggleTopic(t)} className={`border-2 border-black px-3 py-2 font-mono text-[10px] font-black uppercase ${topicDraft.includes(t)?'bg-[var(--color-primary)]':'bg-white'}`}>{topicDraft.includes(t)?'✓ ':''}{t}</button>)}</div><button disabled={!topicDraft.length||topicSaving} onClick={()=>void start()} className="mt-4 border-2 border-black bg-black text-white px-4 py-3 font-mono text-[10px] font-black uppercase disabled:opacity-40">{topicSaving?'SAVING…':'START PERSONALIZATION →'}</button></div></section>}
  <section className="border-b-4 border-black bg-neutral-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-6"><div className="flex flex-col xl:flex-row xl:items-end xl:justify-between gap-4"><div><div className="font-mono text-[9px] font-black uppercase text-neutral-500">OFFSCRPT DISCOVERY ENGINE</div><h2 className="font-display font-black text-4xl sm:text-5xl uppercase tracking-tight">YOUR FEED</h2><p className="font-mono text-[10px] mt-1">One adaptive feed for recommendations, following, latest stories, trending content and community activity.</p></div><div className="flex flex-wrap gap-2">{(['algorithmic','chronological'] as FeedMode[]).map(m=><button key={m} type="button" onClick={()=>void changeMode(m)} className={`border-2 border-black px-3 py-2 font-mono text-[9px] font-black uppercase ${feedMode===m?'bg-[var(--color-primary)]':'bg-white'}`}>{m}</button>)}</div></div><div className="flex gap-2 overflow-x-auto pt-5 pb-1">{[['for-you','FOR YOU'],['following','FOLLOWING'],['latest','LATEST'],['trending','TRENDING'],['discussions','DISCUSSIONS'],['communities','COMMUNITIES']].map(([id,label])=><button key={id} type="button" onClick={()=>setFeedTab(id as FeedTab)} className={`shrink-0 border-2 border-black px-3 py-2 font-mono text-[10px] font-black uppercase ${feedTab===id?'bg-black text-white':'bg-white hover:bg-[var(--color-primary)]'}`}>{label}</button>)}</div></div></section>
  {continueArticle&&<section className="max-w-7xl mx-auto px-4 sm:px-6 py-5 border-b-4 border-black"><div className="border-4 border-black bg-black text-white p-5 neo-shadow-lg flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="font-mono text-[9px] text-[var(--color-primary)] font-black"><Clock3 className="inline w-3 h-3"/> CONTINUE READING</div><h2 className="font-display font-black text-3xl uppercase">{continueArticle.title}</h2></div><button type="button" onClick={()=>onNavigate('article',continueArticle.slug)} className="border-2 border-black bg-[var(--color-primary)] text-black px-5 py-3 font-mono text-[10px] font-black">RESUME →</button></div></section>}
  <section className="max-w-7xl mx-auto px-4 sm:px-6 py-7 border-b-4 border-black">
    {feedTab==='following'&&!userAuth&&<div className="mb-4 border-4 border-black bg-[var(--color-primary)] p-4 font-mono text-[10px] font-black uppercase">Sign in to personalize your following feed. Showing latest public content below.</div>}
    <div className="flex items-center justify-between gap-4 mb-5"><div><div className="font-mono text-[9px] font-black uppercase flex items-center gap-1"><Sparkles className="w-3 h-3"/> LIVE DISCOVERY</div><h2 className="font-display font-black text-3xl uppercase">{feedTab==='for-you'?'FOR YOU':feedTab==='following'?'FROM PEOPLE YOU FOLLOW':feedTab==='latest'?'LATEST':feedTab==='trending'?'TRENDING NOW':feedTab==='discussions'?'POPULAR DISCUSSIONS':'YOUR COMMUNITIES'}</h2></div><div className="font-mono text-[9px] uppercase">{algorithmic?'ALGORITHMIC':'CHRONOLOGICAL'}</div></div>
    {feedTab==='discussions' ? (
      extrasLoading&&!discussions.length ? <div className="border-4 border-black p-8 bg-white font-mono text-xs">LOADING DISCUSSIONS…</div> :
      discussions.length ? <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{discussions.slice(0,8).map(p=><PostMini key={p.id} p={p} userId={userAuth?.uid} onOpen={()=>onNavigate('community_post',p.id)}/>)}</div> : <div className="border-4 border-black p-8 bg-white font-mono text-xs">NO DISCUSSIONS YET</div>
    ) : feedTab==='communities' ? (
      extrasLoading&&!communities.length ? <div className="border-4 border-black p-8 bg-white font-mono text-xs">LOADING COMMUNITIES…</div> :
      communities.length ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{communities.slice(0,6).map(c=><CommunityMini key={c.id} c={c} onOpen={()=>onNavigate('community',c.slug||c.id)}/>)}</div> : <div className="border-4 border-black p-8 bg-white font-mono text-xs">NO COMMUNITIES TO SHOW</div>
    ) : feedTab==='trending' ? (
      <>
        <div className="flex flex-wrap gap-2 mb-5">{(['articles','posts','questions','creators','communities','series','topics'] as TrendingKind[]).map(k=><button key={k} type="button" onClick={()=>setTrendingKind(k)} className={`border-2 border-black px-3 py-2 font-mono text-[9px] font-black uppercase ${trendingKind===k?'bg-[var(--color-primary)]':'bg-white'}`}>{k}</button>)}</div>
        {trendingKind==='creators' ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{creatorRadarSorted.map(c=><button key={c.uid||c.username||c.name} type="button" onClick={()=>c.username&&onNavigate('creator',c.username)} className="text-left border-4 border-black bg-white p-5 hover:bg-[var(--color-primary)]"><div className="flex items-center gap-3"><div className="w-12 h-12 border-2 border-black overflow-hidden bg-neutral-100 grid place-items-center font-display font-black">{c.avatar?<img src={c.avatar} alt="" className="w-full h-full object-cover"/>:c.name.charAt(0)}</div><div><div className="font-display font-black uppercase">{c.name}</div><div className="font-mono text-[9px]">{c.username?`@${c.username}`:'CREATOR'}</div></div></div><div className="font-mono text-[9px] mt-4">{c.articles} ARTICLES · {c.views.toLocaleString()} VIEWS · {c.recent} NEW</div></button>)}</div>
        :trendingKind==='topics' ? <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-3">{trendingTopicRows.map(([name,count])=><button key={name} type="button" onClick={()=>onNavigate('topic',name)} className="text-left border-4 border-black bg-white p-5 hover:bg-[var(--color-primary)]"><div className="font-mono text-[9px]">TOPIC</div><div className="font-display font-black text-2xl uppercase mt-1">{name}</div><div className="font-mono text-[9px] mt-3">TREND SCORE {Math.round(count)}</div></button>)}</div>
        :trendingKind==='communities' ? <>{extrasLoading&&!communities.length?<div className="border-4 border-black p-8 bg-white font-mono text-xs">LOADING COMMUNITIES…</div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{communities.slice(0,6).map(c=><CommunityMini key={c.id} c={c} onOpen={()=>onNavigate('community',c.slug||c.id)}/>)}</div>}</>
        :trendingKind==='posts' ? <>{extrasLoading&&!discussions.length?<div className="border-4 border-black p-8 bg-white font-mono text-xs">LOADING POSTS…</div>:<div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{(trendingItems as CommunityPost[]).map(p=><PostMini key={p.id} p={p} userId={userAuth?.uid} onOpen={()=>onNavigate('community_post',p.id)}/>)}</div>}</>
        :trendingKind==='questions' ? <>{extrasLoading&&!questions.length?<div className="border-4 border-black p-8 bg-white font-mono text-xs">LOADING QUESTIONS…</div>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{(trendingItems as SocialQuestion[]).map(q=><button key={q.id} type="button" onClick={()=>onNavigate('social')} className="text-left border-4 border-black bg-white p-5 hover:bg-[var(--color-primary)]"><div className="font-mono text-[9px]">QUESTION · {q.answersCount||0} ANSWERS</div><h3 className="font-display font-black text-xl uppercase mt-1 line-clamp-3">{q.title}</h3><p className="font-mono text-[9px] mt-3">{Number(q.upvotesCount||0)} UPVOTES · {Number(q.followersCount||0)} FOLLOWERS</p></button>)}</div>}</>
        :trendingKind==='series' ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{(trendingItems as Series[]).map(s=><button key={s.id} type="button" onClick={()=>onNavigate('series',s.slug||s.id)} className="text-left border-4 border-black bg-white overflow-hidden hover:bg-[var(--color-primary)]">{s.coverImage?<img src={s.coverImage} alt="" className="w-full aspect-[16/9] object-cover border-b-4 border-black"/>:<div className="w-full aspect-[16/9] bg-neutral-100 border-b-4 border-black"/>}<div className="p-4"><div className="font-mono text-[9px]">SERIES · {s.articleCount} PARTS</div><h3 className="font-display font-black text-xl uppercase mt-1 line-clamp-2">{s.title}</h3></div></button>)}</div>
        : <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{displayedArticles.map(a=><Mini key={a.slug} a={a} onOpen={()=>onNavigate('article',a.slug)} reason="TRENDING SIGNALS" onMenu={userAuth?setOptionArticle:undefined}/>)}</div>}
      </>
    ) : (
      displayedArticles.length ? <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{displayedArticles.map(a=><Mini key={a.slug} a={a} onOpen={()=>onNavigate('article',a.slug)} reason={feedTab==='for-you'?(sections.find(s=>s.title==='FOR YOU')?.reason||'PERSONALIZED FOR YOU'):undefined} onMenu={feedTab==='for-you'&&userAuth?setOptionArticle:undefined}/>)}</div> : <div className="border-4 border-black bg-white p-8 font-mono text-xs">{feedTab==='following'?'No followed creators yet. Follow creators to build this feed.':'No content matches this feed yet.'}</div>
    )}
  </section>
  {optionArticle&&<div className="fixed inset-0 z-[100] bg-black/50 flex items-end sm:items-center justify-center p-4" role="dialog" aria-modal="true" aria-label="Recommendation controls" onClick={()=>setOptionArticle(null)}><div className="w-full max-w-md border-4 border-black bg-white neo-shadow-lg p-5" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><div className="font-mono text-[9px] font-black uppercase">RECOMMENDATION CONTROLS</div><h3 className="font-display font-black text-2xl uppercase mt-1">{optionArticle.title}</h3></div><button type="button" onClick={()=>setOptionArticle(null)} aria-label="Close"><X/></button></div><div className="grid gap-2 mt-5"><button type="button" onClick={()=>void mutatePref('hidden',optionArticle)} className="border-2 border-black p-3 text-left font-mono text-[10px] font-black uppercase">Not interested</button><button type="button" onClick={()=>void mutatePref('topic',optionArticle)} className="border-2 border-black p-3 text-left font-mono text-[10px] font-black uppercase">Show less like this</button><button type="button" onClick={()=>void mutatePref('creator',optionArticle)} className="border-2 border-black p-3 text-left font-mono text-[10px] font-black uppercase">Mute creator @{optionArticle.author?.username||optionArticle.author?.name}</button><button type="button" onClick={()=>void mutatePref('community',optionArticle)} className="border-2 border-black p-3 text-left font-mono text-[10px] font-black uppercase">Mute community</button><div className="border-2 border-black p-3 bg-neutral-50"><div className="font-mono text-[9px] font-black uppercase mb-1">WHY THIS?</div><div className="font-mono text-[10px]">{sections.find(s=>s.title==='FOR YOU')?.reason||'Recommended from your reading profile.'}</div></div></div></div></div>}
  {secondarySections.slice(0,6).map(s=><section key={s.title} className="max-w-7xl mx-auto px-4 sm:px-6 py-8 border-b-4 border-black"><div className="mb-5"><div className="font-mono text-[9px] font-black uppercase"><Sparkles className="inline w-3 h-3"/> DATA-DRIVEN DISCOVERY</div><h2 className="font-display font-black text-3xl uppercase">{s.title}</h2>{s.reason&&<div className="font-mono text-[9px] mt-1">{s.reason}</div>}</div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{s.articles.map(a=><Mini key={a.slug} a={a} onOpen={()=>onNavigate('article',a.slug)} reason={s.reason}/>)}</div></section>)}
  {creatorRadarSorted.length>0&&<section className="max-w-7xl mx-auto px-4 sm:px-6 py-8 border-b-4 border-black"><div className="mb-5"><div className="font-mono text-[9px] font-black uppercase">CREATOR RADAR</div><h2 className="font-display font-black text-3xl uppercase">RISING CREATORS</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{creatorRadarSorted.slice(0,3).map(c=><button key={c.uid||c.username||c.name} type="button" onClick={()=>c.username&&onNavigate('creator',c.username)} className="text-left border-4 border-black bg-white p-5 hover:bg-[var(--color-primary)]"><div className="font-display font-black text-xl uppercase">{c.name}</div><div className="font-mono text-[9px] mt-1">{c.username?`@${c.username}`:'CREATOR'}</div><div className="font-mono text-[9px] mt-3">{c.articles} ARTICLES · {c.recent} RECENT · {c.views.toLocaleString()} VIEWS</div></button>)}</div></section>}
 </>;
};
