import React,{useEffect,useState} from 'react';
import {CommunityUser,PageView} from '../types';
import {CommunityPost,} from '../types';
import {getCommunities,createCommunity,joinCommunity,leaveCommunity,isCommunityMember,getCommunityPosts,createCommunityPost,getQuestions,createQuestion,getAnswers,createAnswer,markBestAnswer,voteAnswer,getTopics,createTopic,toggleTopicFollow,getMessages,sendMessage,reportContent,SocialCommunity,CommunityFeedPost,SocialQuestion,SocialAnswer,SocialTopic,SocialMessage,subscribeMessages} from '../lib/social';
import {getAllCommunityUsers} from '../lib/community';
import {Users,MessageSquare,HelpCircle,Hash,Plus,Send,ArrowUp,ArrowDown,Check,Search,Shield,Mail,BookOpen,TrendingUp,X} from 'lucide-react';
import {formatDisplayDate} from '../lib/dateUtils';

interface Props{userProfile:CommunityUser|null;onNavigate:(page:PageView,param?:string)=>void;}
type Tab='feed'|'communities'|'questions'|'topics'|'messages';

export const SocialHubView:React.FC<Props>=({userProfile,onNavigate})=>{
 const [tab,setTab]=useState<Tab>('feed'); const [communities,setCommunities]=useState<SocialCommunity[]>([]); const [selected,setSelected]=useState<SocialCommunity|null>(null); const [communityPosts,setCommunityPosts]=useState<CommunityFeedPost[]>([]); const [questions,setQuestions]=useState<SocialQuestion[]>([]); const [topics,setTopics]=useState<SocialTopic[]>([]); const [users,setUsers]=useState<CommunityUser[]>([]); const [messages,setMessages]=useState<SocialMessage[]>([]); const [activeChat,setActiveChat]=useState<CommunityUser|null>(null); const [answers,setAnswers]=useState<Record<string,SocialAnswer[]>>({}); const [loading,setLoading]=useState(false); const [search,setSearch]=useState('');
 const [communityForm,setCommunityForm]=useState(false); const [questionForm,setQuestionForm]=useState(false); const [topicForm,setTopicForm]=useState(false); const [postForm,setPostForm]=useState(false); const [answerFor,setAnswerFor]=useState<string|null>(null);
 const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [title,setTitle]=useState(''); const [content,setContent]=useState(''); const [topicsInput,setTopicsInput]=useState(''); const [message,setMessage]=useState('');
 useEffect(()=>{setLoading(true);Promise.all([getCommunities(),getQuestions(),getTopics(),getAllCommunityUsers()]).then(([c,q,t,u])=>{setCommunities(c);setQuestions(q);setTopics(t);setUsers(u);}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!userProfile)return;return subscribeMessages(userProfile.uid,setMessages);},[userProfile]);
 useEffect(()=>{if(selected){getCommunityPosts(selected.id).then(setCommunityPosts);}},[selected]);
 const requireAuth=()=>{if(!userProfile){alert('Sign in to use this feature.');return false;}return true;};
 const refresh=async()=>{const [c,q,t]=await Promise.all([getCommunities(),getQuestions(),getTopics()]);setCommunities(c);setQuestions(q);setTopics(t);};
 const createC=async()=>{if(!requireAuth()||!name.trim())return;try{const c=await createCommunity(userProfile!,name,description);setCommunities(x=>[c,...x]);setName('');setDescription('');setCommunityForm(false);setSelected(c);}catch(e:any){alert(e.message)}};
 const createQ=async()=>{if(!requireAuth()||!title.trim()||!content.trim())return;try{const q=await createQuestion(userProfile!,title,content,topicsInput.split(',').map(x=>x.trim()));setQuestions(x=>[q,...x]);setTitle('');setContent('');setTopicsInput('');setQuestionForm(false);}catch(e:any){alert(e.message)}};
 const createT=async()=>{if(!requireAuth()||!name.trim())return;try{await createTopic(userProfile!,name,description);await refresh();setName('');setDescription('');setTopicForm(false);}catch(e:any){alert(e.message)}};
 const createP=async()=>{if(!requireAuth()||!selected||!title.trim()||!content.trim())return;try{const p=await createCommunityPost(selected.id,userProfile!,title,content);setCommunityPosts(x=>[p,...x]);setTitle('');setContent('');setPostForm(false);await refresh();}catch(e:any){alert(e.message)}};
 const loadAnswers=async(qid:string)=>{setAnswers(x=>({...x,[qid]:x[qid]||[]}));const a=await getAnswers(qid);setAnswers(x=>({...x,[qid]:a}));};
 const answer=async(qid:string)=>{if(!requireAuth()||!content.trim())return;try{const a=await createAnswer(qid,userProfile!,content);setAnswers(x=>({...x,[qid]:[...(x[qid]||[]),a]}));setQuestions(x=>x.map(q=>q.id===qid?{...q,answersCount:q.answersCount+1}:q));setContent('');setAnswerFor(null);}catch(e:any){alert(e.message)}};
 const filteredUsers=users.filter(u=>`${u.username} ${u.displayName}`.toLowerCase().includes(search.toLowerCase()));
 const renderTabs=<div className="flex flex-wrap gap-2 mb-6">{[['feed','Feed',TrendingUp],['communities','Communities',Users],['questions','Questions',HelpCircle],['topics','Topics',Hash],['messages','Messages',Mail]].map(([v,l,I]:any)=><button key={v} onClick={()=>setTab(v)} className={`px-4 py-2 border-2 border-black font-mono text-xs font-black uppercase flex items-center gap-2 ${tab===v?'bg-[var(--color-primary)] neo-shadow-sm':'bg-white'}`}><I className="w-4 h-4"/>{l}</button>)}</div>;
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
  <div className="border-4 border-black bg-black text-white p-5 sm:p-8 mb-8 neo-shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="font-mono text-xs text-[var(--color-primary)] font-black uppercase">OFFSCRPT SOCIAL GRAPH</div><h1 className="font-display font-black text-4xl sm:text-6xl uppercase leading-none mt-2">Social / Knowledge</h1><p className="font-mono text-xs sm:text-sm text-neutral-300 mt-3 max-w-2xl">A single network for fast posts, deep communities, questions, answers, topics and direct conversations.</p></div><div className="flex gap-2 flex-wrap"><button onClick={()=>{if(!requireAuth())return;setName('');setDescription('');setCommunityForm(true)}} className="px-3 py-2 bg-[var(--color-primary)] text-black border-2 border-white font-mono text-xs font-black">+ COMMUNITY</button><button onClick={()=>{if(!requireAuth())return;setTitle('');setContent('');setQuestionForm(true)}} className="px-3 py-2 bg-white text-black border-2 border-white font-mono text-xs font-black">+ QUESTION</button></div></div></div>
  {renderTabs}
  {tab==='feed'&&<div className="grid lg:grid-cols-[1fr_320px] gap-6"><section className="space-y-4"><div className="bg-white border-4 border-black p-5"><div className="font-display font-black uppercase text-xl">Your Network</div><p className="font-mono text-xs text-neutral-500 mt-1">Communities, questions and people to jump into.</p></div>{communities.slice(0,4).map(c=><button key={c.id} onClick={()=>{setSelected(c);setTab('communities')}} className="w-full text-left bg-white border-2 border-black p-5 hover:bg-[var(--color-primary)]"><div className="flex justify-between"><div><div className="font-display font-black text-lg">c/{c.slug}</div><div className="font-mono text-xs text-neutral-500">{c.membersCount} members · {c.postsCount} posts</div></div><Users className="w-5 h-5"/></div><p className="text-sm mt-3 line-clamp-2">{c.description}</p></button>)}{questions.slice(0,5).map(q=><button key={q.id} onClick={()=>{setTab('questions');loadAnswers(q.id)}} className="w-full text-left bg-white border-2 border-black p-5"><div className="font-mono text-[10px] uppercase font-black text-neutral-500">Question · {q.answersCount} answers</div><div className="font-display font-black text-xl mt-1">{q.title}</div><div className="font-mono text-xs mt-3">▲ {q.upvotesCount} · {q.followersCount} following</div></button>)}</section><aside className="space-y-4"><div className="border-4 border-black bg-[var(--color-primary)] p-5"><div className="font-display font-black uppercase">Trending Topics</div>{topics.slice(0,8).map(t=><button key={t.id} onClick={()=>setTab('topics')} className="block w-full text-left mt-3 font-mono text-xs font-bold hover:underline">#{t.slug} <span className="float-right">{t.followersCount}</span></button>)}</div><div className="border-2 border-black p-5"><div className="font-display font-black uppercase">People</div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people" className="w-full mt-3 border-2 border-black p-2 font-mono text-xs"/>{filteredUsers.slice(0,6).map(u=><button key={u.uid} onClick={()=>onNavigate('community_profile',u.username)} className="flex items-center gap-2 w-full mt-3 text-left"><div className="w-8 h-8 border-2 border-black rounded-full overflow-hidden">{u.photoURL&&<img src={u.photoURL} className="w-full h-full object-cover"/>}</div><div className="min-w-0"><div className="font-bold text-sm truncate">{u.displayName}</div><div className="font-mono text-[10px]">@{u.username}</div></div></button>)}</div></aside></div>}
  {tab==='communities'&&<div className="grid lg:grid-cols-[330px_1fr] gap-6"><div className="space-y-3">{communities.filter(c=>`${c.name} ${c.slug}`.toLowerCase().includes(search.toLowerCase())).map(c=><button key={c.id} onClick={()=>setSelected(c)} className={`w-full text-left border-2 border-black p-4 ${selected?.id===c.id?'bg-[var(--color-primary)]':'bg-white'}`}><div className="font-display font-black">c/{c.slug}</div><div className="font-mono text-[10px] mt-1">{c.membersCount} MEMBERS · {c.postsCount} POSTS</div><p className="text-xs mt-2">{c.description}</p></button>)}</div><div>{!selected?<div className="border-4 border-black p-10 text-center font-mono text-sm">SELECT A COMMUNITY.</div>:<CommunityPanel community={selected} user={userProfile} posts={communityPosts} onJoin={async()=>{if(!userProfile)return;await joinCommunity(selected.id,userProfile);setSelected({...selected,membersCount:selected.membersCount+1});await refresh();}} onLeave={async()=>{if(!userProfile)return;try{await leaveCommunity(selected.id,userProfile.uid);setSelected({...selected,membersCount:Math.max(0,selected.membersCount-1)});await refresh();}catch(e:any){alert(e.message)}}} onPost={()=>{setTitle('');setContent('');setPostForm(true)}} onNavigate={onNavigate} onReport={async()=>{if(userProfile)await reportContent(userProfile,'community',selected.id,'User report')}} />}</div></div>}
  {tab==='questions'&&<div className="grid lg:grid-cols-[1fr_330px] gap-6"><div className="space-y-4">{questions.map(q=><div key={q.id} className="bg-white border-2 border-black p-5"><div className="font-mono text-[10px] uppercase text-neutral-500">Q · @{q.authorUsername} · {formatDisplayDate(q.createdAt)}</div><h2 className="font-display font-black text-2xl mt-1">{q.title}</h2><p className="text-sm mt-3 whitespace-pre-wrap">{q.details}</p><div className="flex flex-wrap gap-2 mt-4">{q.topics.map(t=><span key={t} className="px-2 py-1 bg-neutral-100 border border-black font-mono text-[10px]">#{t}</span>)}</div><div className="flex gap-2 mt-5"><button onClick={()=>{loadAnswers(q.id);setAnswerFor(answerFor===q.id?null:q.id)}} className="px-3 py-2 border-2 border-black font-mono text-xs font-bold">{q.answersCount} ANSWERS</button><button onClick={()=>{if(requireAuth())setContent('')}} className="px-3 py-2 border-2 border-black font-mono text-xs">▲ {q.upvotesCount}</button></div>{answerFor===q.id&&<div className="mt-5 border-t-2 border-black pt-4"><textarea value={content} onChange={e=>setContent(e.target.value)} className="w-full border-2 border-black p-3 min-h-28" placeholder="Write a useful answer..."/><button onClick={()=>answer(q.id)} className="mt-2 px-4 py-2 bg-[var(--color-primary)] border-2 border-black font-mono text-xs font-black">POST ANSWER</button></div>}{(answers[q.id]||[]).map(a=><div key={a.id} className={`mt-4 p-4 border-2 ${a.isBest?'border-black bg-[var(--color-secondary)]':'border-neutral-300'}`}><div className="font-mono text-[10px]">@{a.authorUsername} · ▲ {a.upvotesCount} ▼ {a.downvotesCount} {a.isBest&&' · ✓ BEST ANSWER'}</div><p className="text-sm whitespace-pre-wrap mt-2">{a.content}</p><div className="flex gap-2 mt-3"><button onClick={async()=>{if(userProfile){await voteAnswer(q.id,a.id,userProfile.uid,'up');await loadAnswers(q.id)}}} className="border border-black px-2 py-1"><ArrowUp className="w-3 h-3"/></button><button onClick={async()=>{if(userProfile){await voteAnswer(q.id,a.id,userProfile.uid,'down');await loadAnswers(q.id)}}} className="border border-black px-2 py-1"><ArrowDown className="w-3 h-3"/></button>{userProfile?.uid===q.authorId&&!a.isBest&&<button onClick={async()=>{await markBestAnswer(q.id,a.id,userProfile.uid);await loadAnswers(q.id)}} className="border border-black px-2 py-1 font-mono text-[10px]">BEST</button>}</div></div>)}</div>)}</div><aside className="border-4 border-black p-5 h-fit"><div className="font-display font-black uppercase">Question Rules</div><ul className="font-mono text-xs space-y-2 mt-3"><li>• Ask one clear question.</li><li>• Add context and constraints.</li><li>• Reward useful answers.</li><li>• Cite sources where useful.</li></ul></aside></div>}
  {tab==='topics'&&<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{topics.map(t=><div key={t.id} className="border-2 border-black bg-white p-5"><div className="font-display font-black text-xl">#{t.slug}</div><p className="text-sm mt-2">{t.description}</p><div className="font-mono text-[10px] mt-4">{t.followersCount} FOLLOWERS</div><button onClick={async()=>{if(userProfile){await toggleTopicFollow(t.id,userProfile);await refresh()}}} className="mt-4 px-3 py-2 bg-[var(--color-primary)] border-2 border-black font-mono text-xs font-black">FOLLOW TOPIC</button></div>)}<button onClick={()=>{if(requireAuth()){setName('');setDescription('');setTopicForm(true)}}} className="border-2 border-dashed border-black p-8 font-display font-black">+ CREATE TOPIC</button></div>}
  {tab==='messages'&&<div className="grid lg:grid-cols-[300px_1fr] border-4 border-black bg-white min-h-[560px]"><div className="border-b-2 lg:border-b-0 lg:border-r-2 border-black p-4">{users.filter(u=>u.uid!==userProfile?.uid).slice(0,30).map(u=><button key={u.uid} onClick={()=>setActiveChat(u)} className={`w-full p-3 text-left flex gap-2 ${activeChat?.uid===u.uid?'bg-[var(--color-primary)]':''}`}><div className="w-8 h-8 rounded-full border-2 border-black overflow-hidden">{u.photoURL&&<img src={u.photoURL} className="w-full h-full object-cover"/>}</div><div><div className="font-bold text-sm">{u.displayName}</div><div className="font-mono text-[10px]">@{u.username}</div></div></button>)}</div><div className="flex flex-col">{!activeChat?<div className="flex-1 grid place-items-center font-mono text-sm">SELECT A PERSON TO MESSAGE.</div>:<><div className="p-4 border-b-2 border-black"><div className="font-display font-black">@{activeChat.username}</div></div><div className="flex-1 p-4 space-y-2 overflow-auto">{messages.filter(m=>m.senderId===activeChat.uid||m.recipientId===activeChat.uid).reverse().map(m=><div key={m.id} className={`max-w-[80%] p-3 border-2 border-black ${m.senderId===userProfile?.uid?'ml-auto bg-[var(--color-primary)]':'bg-neutral-100'}`}><div className="text-sm whitespace-pre-wrap">{m.content}</div><div className="font-mono text-[9px] mt-1">{formatDisplayDate(m.createdAt)}</div></div>)}</div><form onSubmit={async e=>{e.preventDefault();if(userProfile){await sendMessage(userProfile,activeChat,message);setMessage('')}}} className="p-3 border-t-2 border-black flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message..." className="flex-1 border-2 border-black p-3"/><button className="px-4 border-2 border-black bg-[var(--color-primary)]"><Send/></button></form></>}</div></div>}
  {communityForm&&<Modal title="Create Community" close={()=>setCommunityForm(false)}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Community name" className="w-full border-2 border-black p-3"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description and purpose" className="w-full border-2 border-black p-3 min-h-28"/><button onClick={createC} className="px-4 py-2 bg-[var(--color-primary)] border-2 border-black font-mono text-xs font-black">CREATE</button></Modal>}
  {questionForm&&<Modal title="Ask a Question" close={()=>setQuestionForm(false)}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Question title" className="w-full border-2 border-black p-3"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Context, constraints, what you've tried..." className="w-full border-2 border-black p-3 min-h-40"/><input value={topicsInput} onChange={e=>setTopicsInput(e.target.value)} placeholder="topics, comma, separated" className="w-full border-2 border-black p-3"/><button onClick={createQ} className="px-4 py-2 bg-[var(--color-primary)] border-2 border-black font-mono text-xs font-black">PUBLISH QUESTION</button></Modal>}
  {topicForm&&<Modal title="Create Topic" close={()=>setTopicForm(false)}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Topic name" className="w-full border-2 border-black p-3"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Topic description" className="w-full border-2 border-black p-3"/><button onClick={createT} className="px-4 py-2 bg-[var(--color-primary)] border-2 border-black font-mono text-xs font-black">CREATE TOPIC</button></Modal>}
  {postForm&&selected&&<Modal title={`Post in c/${selected.slug}`} close={()=>setPostForm(false)}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Post title" className="w-full border-2 border-black p-3"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Start a discussion..." className="w-full border-2 border-black p-3 min-h-40"/><button onClick={createP} className="px-4 py-2 bg-[var(--color-primary)] border-2 border-black font-mono text-xs font-black">PUBLISH</button></Modal>}
 </div>
}

const Modal:React.FC<{title:string;close:()=>void;children:React.ReactNode}>=({title,close,children})=><div className="fixed inset-0 z-[100] bg-black/60 p-4 grid place-items-center"><div className="bg-white border-4 border-black w-full max-w-xl neo-shadow-lg"><div className="bg-[var(--color-primary)] border-b-4 border-black p-4 flex justify-between"><h2 className="font-display font-black uppercase">{title}</h2><button onClick={close}><X/></button></div><div className="p-5 space-y-4">{children}</div></div></div>;

const CommunityPanel:React.FC<any>=({community,user,posts,onJoin,onLeave,onPost,onNavigate,onReport})=>{const [member,setMember]=useState(false);useEffect(()=>{if(user)isCommunityMember(community.id,user.uid).then(setMember)},[community.id,user]);return <div className="border-4 border-black bg-white"><div className="bg-[var(--color-primary)] p-5 border-b-4 border-black"><div className="font-mono text-xs font-black">c/{community.slug}</div><h2 className="font-display font-black text-3xl uppercase">{community.name}</h2><p className="text-sm mt-2">{community.description}</p><div className="flex gap-2 mt-4"><button onClick={async()=>{if(member){await onLeave();setMember(false)}else{await onJoin();setMember(true)}}} className="px-3 py-2 border-2 border-black bg-white font-mono text-xs font-black">{member?'LEAVE':'JOIN'}</button>{member&&<button onClick={onPost} className="px-3 py-2 border-2 border-black bg-black text-white font-mono text-xs font-black">+ POST</button>}<button onClick={onReport} className="px-3 py-2 border-2 border-black bg-white font-mono text-xs">REPORT</button></div></div><div className="p-5 space-y-4">{posts.length===0?<div className="font-mono text-xs text-neutral-500">NO POSTS YET.</div>:posts.map((p:CommunityFeedPost)=><article key={p.id} className="border-2 border-black p-4"><button onClick={()=>onNavigate('community_profile',p.authorUsername)} className="font-mono text-[10px] font-black">@{p.authorUsername}</button><h3 className="font-display font-black text-xl mt-1">{p.title}</h3><p className="text-sm mt-2 whitespace-pre-wrap">{p.content}</p><div className="font-mono text-[10px] mt-4">▲ {p.score} · 💬 {p.commentsCount} · {formatDisplayDate(p.createdAt)}</div></article>)}</div></div>};
