import React,{useMemo,useState} from 'react';
import type {BookmarkCollection,VaultHighlight,VaultNote} from '../types';
import { addToVaultCollection, buildVaultCitation, createVaultCollection, deleteVaultCollection, updateHighlightCollections, updateVaultNoteCollections } from '../lib/vault';
import { notifyToast } from '../lib/toast';
import { FolderPlus, Quote, Trash2 } from 'lucide-react';

export const VaultWorkspace:React.FC<{uid:string;collections:BookmarkCollection[];setCollections:React.Dispatch<React.SetStateAction<any[]>>;highlights:VaultHighlight[];setHighlights:React.Dispatch<React.SetStateAction<VaultHighlight[]>>;notes:VaultNote[];setNotes:React.Dispatch<React.SetStateAction<VaultNote[]>>;}>=({uid,collections,setCollections,highlights,setHighlights,notes,setNotes})=>{
 const [name,setName]=useState(''); const [q,setQ]=useState('');
 const filteredH=useMemo(()=>highlights.filter(h=>!q||(`${h.articleTitle} ${h.quote}`).toLowerCase().includes(q.toLowerCase())),[highlights,q]);
 const filteredN=useMemo(()=>notes.filter(n=>!q||(`${n.title} ${n.body}`).toLowerCase().includes(q.toLowerCase())),[notes,q]);
 const create=async()=>{try{const c=await createVaultCollection(uid,name);setCollections(x=>[...x,c]);setName('');notifyToast('Collection created.','success')}catch(e){notifyToast(e instanceof Error?e.message:'Could not create collection.','error')}};
 const addH=async(id:string,col:string)=>{try{const h=highlights.find(x=>x.id===id);if(!h)return;await addToVaultCollection(uid,col,'highlight',id);await updateHighlightCollections(uid,id,Array.from(new Set([...(h.collectionIds||[]),col])));setHighlights(x=>x.map(v=>v.id===id?{...v,collectionIds:Array.from(new Set([...(v.collectionIds||[]),col]))}:v));notifyToast('Highlight added to collection.','success')}catch(e){notifyToast(e instanceof Error?e.message:'Could not update collection.','error')}};
 const addN=async(id:string,col:string)=>{try{const n=notes.find(x=>x.id===id);if(!n)return;await addToVaultCollection(uid,col,'note',id);await updateVaultNoteCollections(uid,id,Array.from(new Set([...(n.collectionIds||[]),col])));setNotes(x=>x.map(v=>v.id===id?{...v,collectionIds:Array.from(new Set([...(v.collectionIds||[]),col]))}:v));notifyToast('Note added to collection.','success')}catch(e){notifyToast(e instanceof Error?e.message:'Could not update collection.','error')}};
 const cite=async(item:any)=>{const c=buildVaultCitation(item);const text=`> ${c.quotedText||item.body}\n\n— ${c.source.title}`;try{await navigator.clipboard.writeText(text);window.dispatchEvent(new CustomEvent('offscrpt:vault-citation',{detail:c}));notifyToast('Citation copied. You can insert it into a composer.','success')}catch{notifyToast('Could not copy citation.','error')}};
 return <div className="mt-6 border-t-4 border-black pt-5 space-y-5"><div className="flex flex-wrap gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search your Vault" className="flex-1 min-w-[180px] border-2 border-black p-2 font-mono text-xs"/><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New collection" className="border-2 border-black p-2 font-mono text-xs"/><button onClick={create} className="border-2 border-black bg-[var(--color-primary)] px-3 font-mono text-[9px] font-black"><FolderPlus className="inline w-3 h-3"/> CREATE</button></div></div><div className="flex flex-wrap gap-2">{collections.map((c:any)=><div key={c.id} className="border-2 border-black px-2 py-1 font-mono text-[9px] bg-white">{c.name}{c.id!=='general'&&<button onClick={()=>void deleteVaultCollection(uid,c.id).then(()=>setCollections(x=>x.filter(v=>v.id!==c.id))).catch(e=>notifyToast(e instanceof Error?e.message:'Could not delete collection.','error'))} className="ml-2" aria-label={`Delete ${c.name}`}><Trash2 className="inline w-3 h-3"/></button>}</div>)}</div><section><div className="font-mono text-[9px] font-black uppercase mb-2">Highlights</div><div className="grid md:grid-cols-2 gap-3">{filteredH.map(h=><div key={h.id} className="border-2 border-black p-3 bg-white"><p className="text-sm italic">“{h.quote}”</p><div className="font-mono text-[8px] mt-2 text-neutral-500 truncate">{h.articleTitle}</div><div className="flex flex-wrap gap-2 mt-2"><button onClick={()=>void cite(h)} className="border-2 border-black px-2 py-1 font-mono text-[8px] font-black"><Quote className="inline w-3 h-3"/> CITE</button>{collections.map((c:any)=><button key={c.id} onClick={()=>void addH(h.id,c.id)} className={`border px-2 py-1 font-mono text-[8px] ${h.collectionIds?.includes(c.id)?'bg-[var(--color-primary)] border-black':'border-black bg-white'}`}>{c.name}</button>)}</div></div>)}</div></section><section><div className="font-mono text-[9px] font-black uppercase mb-2">Notes</div><div className="grid md:grid-cols-2 gap-3">{filteredN.map(n=><div key={n.id} className="border-2 border-black p-3 bg-white"><div className="font-display font-black uppercase">{n.title}</div><p className="text-sm mt-1 line-clamp-4">{n.body}</p><div className="flex flex-wrap gap-2 mt-2"><button onClick={()=>void cite(n)} className="border-2 border-black px-2 py-1 font-mono text-[8px] font-black"><Quote className="inline w-3 h-3"/> CITE</button>{collections.map((c:any)=><button key={c.id} onClick={()=>void addN(n.id,c.id)} className={`border px-2 py-1 font-mono text-[8px] ${n.collectionIds?.includes(c.id)?'bg-[var(--color-primary)] border-black':'border-black bg-white'}`}>{c.name}</button>)}</div></div>)}</div></section></div>
};
